// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1RolesReader is a Reader for the GetAPIV1Roles structure.
type GetAPIV1RolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/roles] GetAPIV1Roles", response, response.Code())
	}
}

// NewGetAPIV1RolesOK creates a GetAPIV1RolesOK with default headers values
func NewGetAPIV1RolesOK() *GetAPIV1RolesOK {
	return &GetAPIV1RolesOK{}
}

/*
GetAPIV1RolesOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1RolesOK struct {
	Payload *models.ApimodelsListRolesResponse
}

// IsSuccess returns true when this get Api v1 roles o k response has a 2xx status code
func (o *GetAPIV1RolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 roles o k response has a 3xx status code
func (o *GetAPIV1RolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 roles o k response has a 4xx status code
func (o *GetAPIV1RolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 roles o k response has a 5xx status code
func (o *GetAPIV1RolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 roles o k response a status code equal to that given
func (o *GetAPIV1RolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 roles o k response
func (o *GetAPIV1RolesOK) Code() int {
	return 200
}

func (o *GetAPIV1RolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/roles][%d] getApiV1RolesOK %s", 200, payload)
}

func (o *GetAPIV1RolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/roles][%d] getApiV1RolesOK %s", 200, payload)
}

func (o *GetAPIV1RolesOK) GetPayload() *models.ApimodelsListRolesResponse {
	return o.Payload
}

func (o *GetAPIV1RolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApimodelsListRolesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
