// Code generated by go-swagger; DO NOT EDIT.

package maintenances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1MaintenancesIDParams creates a new GetAPIV1MaintenancesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1MaintenancesIDParams() *GetAPIV1MaintenancesIDParams {
	return &GetAPIV1MaintenancesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1MaintenancesIDParamsWithTimeout creates a new GetAPIV1MaintenancesIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1MaintenancesIDParamsWithTimeout(timeout time.Duration) *GetAPIV1MaintenancesIDParams {
	return &GetAPIV1MaintenancesIDParams{
		timeout: timeout,
	}
}

// NewGetAPIV1MaintenancesIDParamsWithContext creates a new GetAPIV1MaintenancesIDParams object
// with the ability to set a context for a request.
func NewGetAPIV1MaintenancesIDParamsWithContext(ctx context.Context) *GetAPIV1MaintenancesIDParams {
	return &GetAPIV1MaintenancesIDParams{
		Context: ctx,
	}
}

// NewGetAPIV1MaintenancesIDParamsWithHTTPClient creates a new GetAPIV1MaintenancesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1MaintenancesIDParamsWithHTTPClient(client *http.Client) *GetAPIV1MaintenancesIDParams {
	return &GetAPIV1MaintenancesIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1MaintenancesIDParams contains all the parameters to send to the API endpoint

	for the get API v1 maintenances ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1MaintenancesIDParams struct {

	/* ID.

	   Maintenance ID (UUID)

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 maintenances ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MaintenancesIDParams) WithDefaults() *GetAPIV1MaintenancesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 maintenances ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MaintenancesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) WithTimeout(timeout time.Duration) *GetAPIV1MaintenancesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) WithContext(ctx context.Context) *GetAPIV1MaintenancesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) WithHTTPClient(client *http.Client) *GetAPIV1MaintenancesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) WithID(id strfmt.UUID) *GetAPIV1MaintenancesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API v1 maintenances ID params
func (o *GetAPIV1MaintenancesIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1MaintenancesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
