// Code generated by go-swagger; DO NOT EDIT.

package maintenances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1MaintenancesCancelReasonsParams creates a new GetAPIV1MaintenancesCancelReasonsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1MaintenancesCancelReasonsParams() *GetAPIV1MaintenancesCancelReasonsParams {
	return &GetAPIV1MaintenancesCancelReasonsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1MaintenancesCancelReasonsParamsWithTimeout creates a new GetAPIV1MaintenancesCancelReasonsParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1MaintenancesCancelReasonsParamsWithTimeout(timeout time.Duration) *GetAPIV1MaintenancesCancelReasonsParams {
	return &GetAPIV1MaintenancesCancelReasonsParams{
		timeout: timeout,
	}
}

// NewGetAPIV1MaintenancesCancelReasonsParamsWithContext creates a new GetAPIV1MaintenancesCancelReasonsParams object
// with the ability to set a context for a request.
func NewGetAPIV1MaintenancesCancelReasonsParamsWithContext(ctx context.Context) *GetAPIV1MaintenancesCancelReasonsParams {
	return &GetAPIV1MaintenancesCancelReasonsParams{
		Context: ctx,
	}
}

// NewGetAPIV1MaintenancesCancelReasonsParamsWithHTTPClient creates a new GetAPIV1MaintenancesCancelReasonsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1MaintenancesCancelReasonsParamsWithHTTPClient(client *http.Client) *GetAPIV1MaintenancesCancelReasonsParams {
	return &GetAPIV1MaintenancesCancelReasonsParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1MaintenancesCancelReasonsParams contains all the parameters to send to the API endpoint

	for the get API v1 maintenances cancel reasons operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1MaintenancesCancelReasonsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 maintenances cancel reasons params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MaintenancesCancelReasonsParams) WithDefaults() *GetAPIV1MaintenancesCancelReasonsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 maintenances cancel reasons params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1MaintenancesCancelReasonsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) WithTimeout(timeout time.Duration) *GetAPIV1MaintenancesCancelReasonsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) WithContext(ctx context.Context) *GetAPIV1MaintenancesCancelReasonsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) WithHTTPClient(client *http.Client) *GetAPIV1MaintenancesCancelReasonsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 maintenances cancel reasons params
func (o *GetAPIV1MaintenancesCancelReasonsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1MaintenancesCancelReasonsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
