// Code generated by go-swagger; DO NOT EDIT.

package maintenances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAPIV1MaintenancesIDStartReader is a Reader for the PostAPIV1MaintenancesIDStart structure.
type PostAPIV1MaintenancesIDStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1MaintenancesIDStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostAPIV1MaintenancesIDStartNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1MaintenancesIDStartBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1MaintenancesIDStartUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1MaintenancesIDStartForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1MaintenancesIDStartConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1MaintenancesIDStartInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostAPIV1MaintenancesIDStartServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/maintenances/{id}/start] PostAPIV1MaintenancesIDStart", response, response.Code())
	}
}

// NewPostAPIV1MaintenancesIDStartNoContent creates a PostAPIV1MaintenancesIDStartNoContent with default headers values
func NewPostAPIV1MaintenancesIDStartNoContent() *PostAPIV1MaintenancesIDStartNoContent {
	return &PostAPIV1MaintenancesIDStartNoContent{}
}

/*
PostAPIV1MaintenancesIDStartNoContent describes a response with status code 204, with default header values.

Maintenance started
*/
type PostAPIV1MaintenancesIDStartNoContent struct {
}

// IsSuccess returns true when this post Api v1 maintenances Id start no content response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 maintenances Id start no content response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start no content response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 maintenances Id start no content response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start no content response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post Api v1 maintenances Id start no content response
func (o *PostAPIV1MaintenancesIDStartNoContent) Code() int {
	return 204
}

func (o *PostAPIV1MaintenancesIDStartNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartNoContent", 204)
}

func (o *PostAPIV1MaintenancesIDStartNoContent) String() string {
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartNoContent", 204)
}

func (o *PostAPIV1MaintenancesIDStartNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1MaintenancesIDStartBadRequest creates a PostAPIV1MaintenancesIDStartBadRequest with default headers values
func NewPostAPIV1MaintenancesIDStartBadRequest() *PostAPIV1MaintenancesIDStartBadRequest {
	return &PostAPIV1MaintenancesIDStartBadRequest{}
}

/*
PostAPIV1MaintenancesIDStartBadRequest describes a response with status code 400, with default header values.

Invalid UUID
*/
type PostAPIV1MaintenancesIDStartBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start bad request response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start bad request response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start bad request response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 maintenances Id start bad request response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start bad request response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 maintenances Id start bad request response
func (o *PostAPIV1MaintenancesIDStartBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartBadRequest %s", 400, payload)
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartBadRequest %s", 400, payload)
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartUnauthorized creates a PostAPIV1MaintenancesIDStartUnauthorized with default headers values
func NewPostAPIV1MaintenancesIDStartUnauthorized() *PostAPIV1MaintenancesIDStartUnauthorized {
	return &PostAPIV1MaintenancesIDStartUnauthorized{}
}

/*
PostAPIV1MaintenancesIDStartUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1MaintenancesIDStartUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start unauthorized response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start unauthorized response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start unauthorized response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 maintenances Id start unauthorized response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start unauthorized response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 maintenances Id start unauthorized response
func (o *PostAPIV1MaintenancesIDStartUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1MaintenancesIDStartUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartUnauthorized %s", 401, payload)
}

func (o *PostAPIV1MaintenancesIDStartUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartUnauthorized %s", 401, payload)
}

func (o *PostAPIV1MaintenancesIDStartUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartForbidden creates a PostAPIV1MaintenancesIDStartForbidden with default headers values
func NewPostAPIV1MaintenancesIDStartForbidden() *PostAPIV1MaintenancesIDStartForbidden {
	return &PostAPIV1MaintenancesIDStartForbidden{}
}

/*
PostAPIV1MaintenancesIDStartForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIV1MaintenancesIDStartForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start forbidden response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start forbidden response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start forbidden response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 maintenances Id start forbidden response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start forbidden response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 maintenances Id start forbidden response
func (o *PostAPIV1MaintenancesIDStartForbidden) Code() int {
	return 403
}

func (o *PostAPIV1MaintenancesIDStartForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartForbidden %s", 403, payload)
}

func (o *PostAPIV1MaintenancesIDStartForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartForbidden %s", 403, payload)
}

func (o *PostAPIV1MaintenancesIDStartForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartConflict creates a PostAPIV1MaintenancesIDStartConflict with default headers values
func NewPostAPIV1MaintenancesIDStartConflict() *PostAPIV1MaintenancesIDStartConflict {
	return &PostAPIV1MaintenancesIDStartConflict{}
}

/*
PostAPIV1MaintenancesIDStartConflict describes a response with status code 409, with default header values.

Forbidden status transition
*/
type PostAPIV1MaintenancesIDStartConflict struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start conflict response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start conflict response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start conflict response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 maintenances Id start conflict response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start conflict response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 maintenances Id start conflict response
func (o *PostAPIV1MaintenancesIDStartConflict) Code() int {
	return 409
}

func (o *PostAPIV1MaintenancesIDStartConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartConflict %s", 409, payload)
}

func (o *PostAPIV1MaintenancesIDStartConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartConflict %s", 409, payload)
}

func (o *PostAPIV1MaintenancesIDStartConflict) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartInternalServerError creates a PostAPIV1MaintenancesIDStartInternalServerError with default headers values
func NewPostAPIV1MaintenancesIDStartInternalServerError() *PostAPIV1MaintenancesIDStartInternalServerError {
	return &PostAPIV1MaintenancesIDStartInternalServerError{}
}

/*
PostAPIV1MaintenancesIDStartInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPIV1MaintenancesIDStartInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start internal server error response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start internal server error response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start internal server error response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 maintenances Id start internal server error response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 maintenances Id start internal server error response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 maintenances Id start internal server error response
func (o *PostAPIV1MaintenancesIDStartInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartInternalServerError %s", 500, payload)
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartInternalServerError %s", 500, payload)
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartServiceUnavailable creates a PostAPIV1MaintenancesIDStartServiceUnavailable with default headers values
func NewPostAPIV1MaintenancesIDStartServiceUnavailable() *PostAPIV1MaintenancesIDStartServiceUnavailable {
	return &PostAPIV1MaintenancesIDStartServiceUnavailable{}
}

/*
PostAPIV1MaintenancesIDStartServiceUnavailable describes a response with status code 503, with default header values.

Auth service unavailable
*/
type PostAPIV1MaintenancesIDStartServiceUnavailable struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start service unavailable response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start service unavailable response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start service unavailable response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 maintenances Id start service unavailable response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 maintenances Id start service unavailable response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the post Api v1 maintenances Id start service unavailable response
func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) Code() int {
	return 503
}

func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartServiceUnavailable %s", 503, payload)
}

func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartServiceUnavailable %s", 503, payload)
}

func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
