// Code generated by go-swagger; DO NOT EDIT.

package maintenances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAPIV1MaintenancesIDStartReader is a Reader for the PostAPIV1MaintenancesIDStart structure.
type PostAPIV1MaintenancesIDStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1MaintenancesIDStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostAPIV1MaintenancesIDStartNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1MaintenancesIDStartBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1MaintenancesIDStartInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/maintenances/{id}/start] PostAPIV1MaintenancesIDStart", response, response.Code())
	}
}

// NewPostAPIV1MaintenancesIDStartNoContent creates a PostAPIV1MaintenancesIDStartNoContent with default headers values
func NewPostAPIV1MaintenancesIDStartNoContent() *PostAPIV1MaintenancesIDStartNoContent {
	return &PostAPIV1MaintenancesIDStartNoContent{}
}

/*
PostAPIV1MaintenancesIDStartNoContent describes a response with status code 204, with default header values.

Maintenance started
*/
type PostAPIV1MaintenancesIDStartNoContent struct {
}

// IsSuccess returns true when this post Api v1 maintenances Id start no content response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 maintenances Id start no content response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start no content response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 maintenances Id start no content response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start no content response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post Api v1 maintenances Id start no content response
func (o *PostAPIV1MaintenancesIDStartNoContent) Code() int {
	return 204
}

func (o *PostAPIV1MaintenancesIDStartNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartNoContent", 204)
}

func (o *PostAPIV1MaintenancesIDStartNoContent) String() string {
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartNoContent", 204)
}

func (o *PostAPIV1MaintenancesIDStartNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1MaintenancesIDStartBadRequest creates a PostAPIV1MaintenancesIDStartBadRequest with default headers values
func NewPostAPIV1MaintenancesIDStartBadRequest() *PostAPIV1MaintenancesIDStartBadRequest {
	return &PostAPIV1MaintenancesIDStartBadRequest{}
}

/*
PostAPIV1MaintenancesIDStartBadRequest describes a response with status code 400, with default header values.

Invalid request or forbidden status transition
*/
type PostAPIV1MaintenancesIDStartBadRequest struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start bad request response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start bad request response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start bad request response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 maintenances Id start bad request response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 maintenances Id start bad request response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 maintenances Id start bad request response
func (o *PostAPIV1MaintenancesIDStartBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartBadRequest %s", 400, payload)
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartBadRequest %s", 400, payload)
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1MaintenancesIDStartInternalServerError creates a PostAPIV1MaintenancesIDStartInternalServerError with default headers values
func NewPostAPIV1MaintenancesIDStartInternalServerError() *PostAPIV1MaintenancesIDStartInternalServerError {
	return &PostAPIV1MaintenancesIDStartInternalServerError{}
}

/*
PostAPIV1MaintenancesIDStartInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPIV1MaintenancesIDStartInternalServerError struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 maintenances Id start internal server error response has a 2xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 maintenances Id start internal server error response has a 3xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 maintenances Id start internal server error response has a 4xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 maintenances Id start internal server error response has a 5xx status code
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 maintenances Id start internal server error response a status code equal to that given
func (o *PostAPIV1MaintenancesIDStartInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 maintenances Id start internal server error response
func (o *PostAPIV1MaintenancesIDStartInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartInternalServerError %s", 500, payload)
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/maintenances/{id}/start][%d] postApiV1MaintenancesIdStartInternalServerError %s", 500, payload)
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1MaintenancesIDStartInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
