// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1NotificationsChannelsReader is a Reader for the GetAPIV1NotificationsChannels structure.
type GetAPIV1NotificationsChannelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1NotificationsChannelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1NotificationsChannelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1NotificationsChannelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1NotificationsChannelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1NotificationsChannelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetAPIV1NotificationsChannelsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/notifications/channels] GetAPIV1NotificationsChannels", response, response.Code())
	}
}

// NewGetAPIV1NotificationsChannelsOK creates a GetAPIV1NotificationsChannelsOK with default headers values
func NewGetAPIV1NotificationsChannelsOK() *GetAPIV1NotificationsChannelsOK {
	return &GetAPIV1NotificationsChannelsOK{}
}

/*
GetAPIV1NotificationsChannelsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1NotificationsChannelsOK struct {
	Payload *models.ApimodelsChannelsResponse
}

// IsSuccess returns true when this get Api v1 notifications channels o k response has a 2xx status code
func (o *GetAPIV1NotificationsChannelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 notifications channels o k response has a 3xx status code
func (o *GetAPIV1NotificationsChannelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 notifications channels o k response has a 4xx status code
func (o *GetAPIV1NotificationsChannelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 notifications channels o k response has a 5xx status code
func (o *GetAPIV1NotificationsChannelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 notifications channels o k response a status code equal to that given
func (o *GetAPIV1NotificationsChannelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 notifications channels o k response
func (o *GetAPIV1NotificationsChannelsOK) Code() int {
	return 200
}

func (o *GetAPIV1NotificationsChannelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsOK %s", 200, payload)
}

func (o *GetAPIV1NotificationsChannelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsOK %s", 200, payload)
}

func (o *GetAPIV1NotificationsChannelsOK) GetPayload() *models.ApimodelsChannelsResponse {
	return o.Payload
}

func (o *GetAPIV1NotificationsChannelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApimodelsChannelsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NotificationsChannelsUnauthorized creates a GetAPIV1NotificationsChannelsUnauthorized with default headers values
func NewGetAPIV1NotificationsChannelsUnauthorized() *GetAPIV1NotificationsChannelsUnauthorized {
	return &GetAPIV1NotificationsChannelsUnauthorized{}
}

/*
GetAPIV1NotificationsChannelsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1NotificationsChannelsUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 notifications channels unauthorized response has a 2xx status code
func (o *GetAPIV1NotificationsChannelsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 notifications channels unauthorized response has a 3xx status code
func (o *GetAPIV1NotificationsChannelsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 notifications channels unauthorized response has a 4xx status code
func (o *GetAPIV1NotificationsChannelsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 notifications channels unauthorized response has a 5xx status code
func (o *GetAPIV1NotificationsChannelsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 notifications channels unauthorized response a status code equal to that given
func (o *GetAPIV1NotificationsChannelsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 notifications channels unauthorized response
func (o *GetAPIV1NotificationsChannelsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1NotificationsChannelsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1NotificationsChannelsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1NotificationsChannelsUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NotificationsChannelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NotificationsChannelsForbidden creates a GetAPIV1NotificationsChannelsForbidden with default headers values
func NewGetAPIV1NotificationsChannelsForbidden() *GetAPIV1NotificationsChannelsForbidden {
	return &GetAPIV1NotificationsChannelsForbidden{}
}

/*
GetAPIV1NotificationsChannelsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1NotificationsChannelsForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 notifications channels forbidden response has a 2xx status code
func (o *GetAPIV1NotificationsChannelsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 notifications channels forbidden response has a 3xx status code
func (o *GetAPIV1NotificationsChannelsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 notifications channels forbidden response has a 4xx status code
func (o *GetAPIV1NotificationsChannelsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 notifications channels forbidden response has a 5xx status code
func (o *GetAPIV1NotificationsChannelsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 notifications channels forbidden response a status code equal to that given
func (o *GetAPIV1NotificationsChannelsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 notifications channels forbidden response
func (o *GetAPIV1NotificationsChannelsForbidden) Code() int {
	return 403
}

func (o *GetAPIV1NotificationsChannelsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsForbidden %s", 403, payload)
}

func (o *GetAPIV1NotificationsChannelsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsForbidden %s", 403, payload)
}

func (o *GetAPIV1NotificationsChannelsForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NotificationsChannelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NotificationsChannelsInternalServerError creates a GetAPIV1NotificationsChannelsInternalServerError with default headers values
func NewGetAPIV1NotificationsChannelsInternalServerError() *GetAPIV1NotificationsChannelsInternalServerError {
	return &GetAPIV1NotificationsChannelsInternalServerError{}
}

/*
GetAPIV1NotificationsChannelsInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAPIV1NotificationsChannelsInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 notifications channels internal server error response has a 2xx status code
func (o *GetAPIV1NotificationsChannelsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 notifications channels internal server error response has a 3xx status code
func (o *GetAPIV1NotificationsChannelsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 notifications channels internal server error response has a 4xx status code
func (o *GetAPIV1NotificationsChannelsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 notifications channels internal server error response has a 5xx status code
func (o *GetAPIV1NotificationsChannelsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 notifications channels internal server error response a status code equal to that given
func (o *GetAPIV1NotificationsChannelsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 notifications channels internal server error response
func (o *GetAPIV1NotificationsChannelsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1NotificationsChannelsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1NotificationsChannelsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1NotificationsChannelsInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NotificationsChannelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NotificationsChannelsServiceUnavailable creates a GetAPIV1NotificationsChannelsServiceUnavailable with default headers values
func NewGetAPIV1NotificationsChannelsServiceUnavailable() *GetAPIV1NotificationsChannelsServiceUnavailable {
	return &GetAPIV1NotificationsChannelsServiceUnavailable{}
}

/*
GetAPIV1NotificationsChannelsServiceUnavailable describes a response with status code 503, with default header values.

Auth service unavailable
*/
type GetAPIV1NotificationsChannelsServiceUnavailable struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 notifications channels service unavailable response has a 2xx status code
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 notifications channels service unavailable response has a 3xx status code
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 notifications channels service unavailable response has a 4xx status code
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 notifications channels service unavailable response has a 5xx status code
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 notifications channels service unavailable response a status code equal to that given
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get Api v1 notifications channels service unavailable response
func (o *GetAPIV1NotificationsChannelsServiceUnavailable) Code() int {
	return 503
}

func (o *GetAPIV1NotificationsChannelsServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1NotificationsChannelsServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/notifications/channels][%d] getApiV1NotificationsChannelsServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1NotificationsChannelsServiceUnavailable) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NotificationsChannelsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
