// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUIV1CalendarParams creates a new GetUIV1CalendarParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUIV1CalendarParams() *GetUIV1CalendarParams {
	return &GetUIV1CalendarParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUIV1CalendarParamsWithTimeout creates a new GetUIV1CalendarParams object
// with the ability to set a timeout on a request.
func NewGetUIV1CalendarParamsWithTimeout(timeout time.Duration) *GetUIV1CalendarParams {
	return &GetUIV1CalendarParams{
		timeout: timeout,
	}
}

// NewGetUIV1CalendarParamsWithContext creates a new GetUIV1CalendarParams object
// with the ability to set a context for a request.
func NewGetUIV1CalendarParamsWithContext(ctx context.Context) *GetUIV1CalendarParams {
	return &GetUIV1CalendarParams{
		Context: ctx,
	}
}

// NewGetUIV1CalendarParamsWithHTTPClient creates a new GetUIV1CalendarParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUIV1CalendarParamsWithHTTPClient(client *http.Client) *GetUIV1CalendarParams {
	return &GetUIV1CalendarParams{
		HTTPClient: client,
	}
}

/*
GetUIV1CalendarParams contains all the parameters to send to the API endpoint

	for the get UI v1 calendar operation.

	Typically these are written to a http.Request.
*/
type GetUIV1CalendarParams struct {

	/* From.

	   Start date

	   Format: date
	*/
	From strfmt.Date

	/* ResourceIds.

	   Resource IDs(uuid)
	*/
	ResourceIds []string

	/* Statuses.

	   Maintenance statuses
	*/
	Statuses []string

	/* To.

	   End date

	   Format: date
	*/
	To strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get UI v1 calendar params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUIV1CalendarParams) WithDefaults() *GetUIV1CalendarParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get UI v1 calendar params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUIV1CalendarParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithTimeout(timeout time.Duration) *GetUIV1CalendarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithContext(ctx context.Context) *GetUIV1CalendarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithHTTPClient(client *http.Client) *GetUIV1CalendarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithFrom(from strfmt.Date) *GetUIV1CalendarParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetFrom(from strfmt.Date) {
	o.From = from
}

// WithResourceIds adds the resourceIds to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithResourceIds(resourceIds []string) *GetUIV1CalendarParams {
	o.SetResourceIds(resourceIds)
	return o
}

// SetResourceIds adds the resourceIds to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetResourceIds(resourceIds []string) {
	o.ResourceIds = resourceIds
}

// WithStatuses adds the statuses to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithStatuses(statuses []string) *GetUIV1CalendarParams {
	o.SetStatuses(statuses)
	return o
}

// SetStatuses adds the statuses to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetStatuses(statuses []string) {
	o.Statuses = statuses
}

// WithTo adds the to to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) WithTo(to strfmt.Date) *GetUIV1CalendarParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get UI v1 calendar params
func (o *GetUIV1CalendarParams) SetTo(to strfmt.Date) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetUIV1CalendarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param from
	qrFrom := o.From
	qFrom := qrFrom.String()
	if qFrom != "" {

		if err := r.SetQueryParam("from", qFrom); err != nil {
			return err
		}
	}

	if o.ResourceIds != nil {

		// binding items for resource_ids
		joinedResourceIds := o.bindParamResourceIds(reg)

		// query array param resource_ids
		if err := r.SetQueryParam("resource_ids", joinedResourceIds...); err != nil {
			return err
		}
	}

	if o.Statuses != nil {

		// binding items for statuses
		joinedStatuses := o.bindParamStatuses(reg)

		// query array param statuses
		if err := r.SetQueryParam("statuses", joinedStatuses...); err != nil {
			return err
		}
	}

	// query param to
	qrTo := o.To
	qTo := qrTo.String()
	if qTo != "" {

		if err := r.SetQueryParam("to", qTo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetUIV1Calendar binds the parameter resource_ids
func (o *GetUIV1CalendarParams) bindParamResourceIds(formats strfmt.Registry) []string {
	resourceIdsIR := o.ResourceIds

	var resourceIdsIC []string
	for _, resourceIdsIIR := range resourceIdsIR { // explode []string

		resourceIdsIIV := resourceIdsIIR // string as string
		resourceIdsIC = append(resourceIdsIC, resourceIdsIIV)
	}

	// items.CollectionFormat: "multi"
	resourceIdsIS := swag.JoinByFormat(resourceIdsIC, "multi")

	return resourceIdsIS
}

// bindParamGetUIV1Calendar binds the parameter statuses
func (o *GetUIV1CalendarParams) bindParamStatuses(formats strfmt.Registry) []string {
	statusesIR := o.Statuses

	var statusesIC []string
	for _, statusesIIR := range statusesIR { // explode []string

		statusesIIV := statusesIIR // string as string
		statusesIC = append(statusesIC, statusesIIV)
	}

	// items.CollectionFormat: "multi"
	statusesIS := swag.JoinByFormat(statusesIC, "multi")

	return statusesIS
}
