// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApiauthmodelsTokenPairResponse apiauthmodels token pair response
//
// swagger:model apiauthmodels.TokenPairResponse
type ApiauthmodelsTokenPairResponse struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this apiauthmodels token pair response
func (m *ApiauthmodelsTokenPairResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apiauthmodels token pair response based on context it is used
func (m *ApiauthmodelsTokenPairResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApiauthmodelsTokenPairResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiauthmodelsTokenPairResponse) UnmarshalBinary(b []byte) error {
	var res ApiauthmodelsTokenPairResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
