// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApiauthmodelsOAuthCallbackJSONResponse apiauthmodels o auth callback JSON response
//
// swagger:model apiauthmodels.OAuthCallbackJSONResponse
type ApiauthmodelsOAuthCallbackJSONResponse struct {

	// original uri
	OriginalURI string `json:"original_uri,omitempty"`

	// token
	Token *ApiauthmodelsTokenPairResponse `json:"token,omitempty"`
}

// Validate validates this apiauthmodels o auth callback JSON response
func (m *ApiauthmodelsOAuthCallbackJSONResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiauthmodelsOAuthCallbackJSONResponse) validateToken(formats strfmt.Registry) error {
	if swag.IsZero(m.Token) { // not required
		return nil
	}

	if m.Token != nil {
		if err := m.Token.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("token")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this apiauthmodels o auth callback JSON response based on the context it is used
func (m *ApiauthmodelsOAuthCallbackJSONResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiauthmodelsOAuthCallbackJSONResponse) contextValidateToken(ctx context.Context, formats strfmt.Registry) error {

	if m.Token != nil {

		if swag.IsZero(m.Token) { // not required
			return nil
		}

		if err := m.Token.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("token")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApiauthmodelsOAuthCallbackJSONResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiauthmodelsOAuthCallbackJSONResponse) UnmarshalBinary(b []byte) error {
	var res ApiauthmodelsOAuthCallbackJSONResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
