// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApiauthmodelsIntrospectRequest apiauthmodels introspect request
//
// swagger:model apiauthmodels.IntrospectRequest
type ApiauthmodelsIntrospectRequest struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`
}

// Validate validates this apiauthmodels introspect request
func (m *ApiauthmodelsIntrospectRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apiauthmodels introspect request based on context it is used
func (m *ApiauthmodelsIntrospectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApiauthmodelsIntrospectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiauthmodelsIntrospectRequest) UnmarshalBinary(b []byte) error {
	var res ApiauthmodelsIntrospectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
