// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApiauthmodelsAuditLog apiauthmodels audit log
//
// swagger:model apiauthmodels.AuditLog
type ApiauthmodelsAuditLog struct {

	// action
	Action EntityAuditAction `json:"action,omitempty"`

	// actor
	Actor string `json:"actor,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// entity id
	EntityID string `json:"entity_id,omitempty"`

	// entity type
	EntityType string `json:"entity_type,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// target id
	TargetID string `json:"target_id,omitempty"`

	// target type
	TargetType string `json:"target_type,omitempty"`
}

// Validate validates this apiauthmodels audit log
func (m *ApiauthmodelsAuditLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiauthmodelsAuditLog) validateAction(formats strfmt.Registry) error {
	if swag.IsZero(m.Action) { // not required
		return nil
	}

	if err := m.Action.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("action")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("action")
		}

		return err
	}

	return nil
}

// ContextValidate validate this apiauthmodels audit log based on the context it is used
func (m *ApiauthmodelsAuditLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApiauthmodelsAuditLog) contextValidateAction(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Action) { // not required
		return nil
	}

	if err := m.Action.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("action")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("action")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApiauthmodelsAuditLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApiauthmodelsAuditLog) UnmarshalBinary(b []byte) error {
	var res ApiauthmodelsAuditLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
