// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApimodelsMaintenance apimodels maintenance
//
// swagger:model apimodels.Maintenance
type ApimodelsMaintenance struct {

	// actual period
	ActualPeriod *ApimodelsPeriod `json:"actual_period,omitempty"`

	// cancel reason
	CancelReason ApimodelsMaintenanceCancelReason `json:"cancel_reason,omitempty"`

	// cancel reason comment
	CancelReasonComment string `json:"cancel_reason_comment,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// impact
	Impact ApimodelsMaintenanceImpact `json:"impact,omitempty"`

	// notify targets
	NotifyTargets *ApimodelsNotifyTargets `json:"notify_targets,omitempty"`

	// planned period
	PlannedPeriod *ApimodelsPeriod `json:"planned_period,omitempty"`

	// resources
	Resources []*ApimodelsResourceRef `json:"resources"`

	// scope
	Scope ApimodelsMaintenanceScope `json:"scope,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// steps
	Steps []*ApimodelsMaintenanceStep `json:"steps"`

	// title
	Title string `json:"title,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this apimodels maintenance
func (m *ApimodelsMaintenance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActualPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCancelReason(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImpact(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotifyTargets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlannedPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSteps(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApimodelsMaintenance) validateActualPeriod(formats strfmt.Registry) error {
	if swag.IsZero(m.ActualPeriod) { // not required
		return nil
	}

	if m.ActualPeriod != nil {
		if err := m.ActualPeriod.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("actual_period")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("actual_period")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) validateCancelReason(formats strfmt.Registry) error {
	if swag.IsZero(m.CancelReason) { // not required
		return nil
	}

	if err := m.CancelReason.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("cancel_reason")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("cancel_reason")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) validateImpact(formats strfmt.Registry) error {
	if swag.IsZero(m.Impact) { // not required
		return nil
	}

	if err := m.Impact.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("impact")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("impact")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) validateNotifyTargets(formats strfmt.Registry) error {
	if swag.IsZero(m.NotifyTargets) { // not required
		return nil
	}

	if m.NotifyTargets != nil {
		if err := m.NotifyTargets.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("notify_targets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("notify_targets")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) validatePlannedPeriod(formats strfmt.Registry) error {
	if swag.IsZero(m.PlannedPeriod) { // not required
		return nil
	}

	if m.PlannedPeriod != nil {
		if err := m.PlannedPeriod.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("planned_period")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("planned_period")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) validateResources(formats strfmt.Registry) error {
	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	for i := 0; i < len(m.Resources); i++ {
		if swag.IsZero(m.Resources[i]) { // not required
			continue
		}

		if m.Resources[i] != nil {
			if err := m.Resources[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsMaintenance) validateScope(formats strfmt.Registry) error {
	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if err := m.Scope.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("scope")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("scope")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) validateSteps(formats strfmt.Registry) error {
	if swag.IsZero(m.Steps) { // not required
		return nil
	}

	for i := 0; i < len(m.Steps); i++ {
		if swag.IsZero(m.Steps[i]) { // not required
			continue
		}

		if m.Steps[i] != nil {
			if err := m.Steps[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("steps" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("steps" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsMaintenance) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this apimodels maintenance based on the context it is used
func (m *ApimodelsMaintenance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActualPeriod(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCancelReason(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImpact(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNotifyTargets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePlannedPeriod(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSteps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApimodelsMaintenance) contextValidateActualPeriod(ctx context.Context, formats strfmt.Registry) error {

	if m.ActualPeriod != nil {

		if swag.IsZero(m.ActualPeriod) { // not required
			return nil
		}

		if err := m.ActualPeriod.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("actual_period")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("actual_period")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateCancelReason(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.CancelReason) { // not required
		return nil
	}

	if err := m.CancelReason.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("cancel_reason")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("cancel_reason")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateImpact(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Impact) { // not required
		return nil
	}

	if err := m.Impact.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("impact")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("impact")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateNotifyTargets(ctx context.Context, formats strfmt.Registry) error {

	if m.NotifyTargets != nil {

		if swag.IsZero(m.NotifyTargets) { // not required
			return nil
		}

		if err := m.NotifyTargets.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("notify_targets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("notify_targets")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidatePlannedPeriod(ctx context.Context, formats strfmt.Registry) error {

	if m.PlannedPeriod != nil {

		if swag.IsZero(m.PlannedPeriod) { // not required
			return nil
		}

		if err := m.PlannedPeriod.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("planned_period")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("planned_period")
			}

			return err
		}
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Resources); i++ {

		if m.Resources[i] != nil {

			if swag.IsZero(m.Resources[i]) { // not required
				return nil
			}

			if err := m.Resources[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if err := m.Scope.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("scope")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("scope")
		}

		return err
	}

	return nil
}

func (m *ApimodelsMaintenance) contextValidateSteps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Steps); i++ {

		if m.Steps[i] != nil {

			if swag.IsZero(m.Steps[i]) { // not required
				return nil
			}

			if err := m.Steps[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("steps" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("steps" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsMaintenance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsMaintenance) UnmarshalBinary(b []byte) error {
	var res ApimodelsMaintenance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
