// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApimodelsUpdateResourceRequest apimodels update resource request
//
// swagger:model apimodels.UpdateResourceRequest
type ApimodelsUpdateResourceRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// external id
	ExternalID string `json:"external_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this apimodels update resource request
func (m *ApimodelsUpdateResourceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apimodels update resource request based on context it is used
func (m *ApimodelsUpdateResourceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsUpdateResourceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsUpdateResourceRequest) UnmarshalBinary(b []byte) error {
	var res ApimodelsUpdateResourceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
