// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ApimodelsMaintenanceStepStatus apimodels maintenance step status
//
// swagger:model apimodels.MaintenanceStepStatus
type ApimodelsMaintenanceStepStatus string

func NewApimodelsMaintenanceStepStatus(value ApimodelsMaintenanceStepStatus) *ApimodelsMaintenanceStepStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ApimodelsMaintenanceStepStatus.
func (m ApimodelsMaintenanceStepStatus) Pointer() *ApimodelsMaintenanceStepStatus {
	return &m
}

const (

	// ApimodelsMaintenanceStepStatusUnknown captures enum value "unknown"
	ApimodelsMaintenanceStepStatusUnknown ApimodelsMaintenanceStepStatus = "unknown"

	// ApimodelsMaintenanceStepStatusPlanned captures enum value "planned"
	ApimodelsMaintenanceStepStatusPlanned ApimodelsMaintenanceStepStatus = "planned"

	// ApimodelsMaintenanceStepStatusStarted captures enum value "started"
	ApimodelsMaintenanceStepStatusStarted ApimodelsMaintenanceStepStatus = "started"

	// ApimodelsMaintenanceStepStatusCompleted captures enum value "completed"
	ApimodelsMaintenanceStepStatusCompleted ApimodelsMaintenanceStepStatus = "completed"

	// ApimodelsMaintenanceStepStatusCanceled captures enum value "canceled"
	ApimodelsMaintenanceStepStatusCanceled ApimodelsMaintenanceStepStatus = "canceled"
)

// for schema
var apimodelsMaintenanceStepStatusEnum []any

func init() {
	var res []ApimodelsMaintenanceStepStatus
	if err := json.Unmarshal([]byte(`["unknown","planned","started","completed","canceled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apimodelsMaintenanceStepStatusEnum = append(apimodelsMaintenanceStepStatusEnum, v)
	}
}

func (m ApimodelsMaintenanceStepStatus) validateApimodelsMaintenanceStepStatusEnum(path, location string, value ApimodelsMaintenanceStepStatus) error {
	if err := validate.EnumCase(path, location, value, apimodelsMaintenanceStepStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this apimodels maintenance step status
func (m ApimodelsMaintenanceStepStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateApimodelsMaintenanceStepStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this apimodels maintenance step status based on context it is used
func (m ApimodelsMaintenanceStepStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
