// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApimodelsConflict apimodels conflict
//
// swagger:model apimodels.Conflict
type ApimodelsConflict struct {

	// maintenance id
	// Format: uuid
	MaintenanceID strfmt.UUID `json:"maintenance_id,omitempty"`

	// overlap end
	// Format: date-time
	OverlapEnd strfmt.DateTime `json:"overlap_end,omitempty"`

	// overlap start
	// Format: date-time
	OverlapStart strfmt.DateTime `json:"overlap_start,omitempty"`

	// resources
	Resources []*ApimodelsResourceRef `json:"resources"`

	// scope
	Scope ApimodelsMaintenanceScope `json:"scope,omitempty"`
}

// Validate validates this apimodels conflict
func (m *ApimodelsConflict) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaintenanceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOverlapEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOverlapStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApimodelsConflict) validateMaintenanceID(formats strfmt.Registry) error {
	if swag.IsZero(m.MaintenanceID) { // not required
		return nil
	}

	if err := validate.FormatOf("maintenance_id", "body", "uuid", m.MaintenanceID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsConflict) validateOverlapEnd(formats strfmt.Registry) error {
	if swag.IsZero(m.OverlapEnd) { // not required
		return nil
	}

	if err := validate.FormatOf("overlap_end", "body", "date-time", m.OverlapEnd.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsConflict) validateOverlapStart(formats strfmt.Registry) error {
	if swag.IsZero(m.OverlapStart) { // not required
		return nil
	}

	if err := validate.FormatOf("overlap_start", "body", "date-time", m.OverlapStart.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsConflict) validateResources(formats strfmt.Registry) error {
	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	for i := 0; i < len(m.Resources); i++ {
		if swag.IsZero(m.Resources[i]) { // not required
			continue
		}

		if m.Resources[i] != nil {
			if err := m.Resources[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsConflict) validateScope(formats strfmt.Registry) error {
	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if err := m.Scope.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("scope")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("scope")
		}

		return err
	}

	return nil
}

// ContextValidate validate this apimodels conflict based on the context it is used
func (m *ApimodelsConflict) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApimodelsConflict) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Resources); i++ {

		if m.Resources[i] != nil {

			if swag.IsZero(m.Resources[i]) { // not required
				return nil
			}

			if err := m.Resources[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsConflict) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if err := m.Scope.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("scope")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("scope")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsConflict) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsConflict) UnmarshalBinary(b []byte) error {
	var res ApimodelsConflict
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
