// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApimodelsChannel apimodels channel
//
// swagger:model apimodels.Channel
type ApimodelsChannel struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// transport
	Transport string `json:"transport,omitempty"`

	// transport channel id
	TransportChannelID string `json:"transport_channel_id,omitempty"`
}

// Validate validates this apimodels channel
func (m *ApimodelsChannel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apimodels channel based on context it is used
func (m *ApimodelsChannel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsChannel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsChannel) UnmarshalBinary(b []byte) error {
	var res ApimodelsChannel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
