// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApimodelsNotifyTargets apimodels notify targets
//
// swagger:model apimodels.NotifyTargets
type ApimodelsNotifyTargets struct {

	// channel ids
	// Example: ["[slack:C0123456"," tg:-10013123]"]
	ChannelIds []string `json:"channel_ids"`
}

// Validate validates this apimodels notify targets
func (m *ApimodelsNotifyTargets) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apimodels notify targets based on context it is used
func (m *ApimodelsNotifyTargets) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsNotifyTargets) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsNotifyTargets) UnmarshalBinary(b []byte) error {
	var res ApimodelsNotifyTargets
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
