// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthRefreshTokenJSONRequest auth refresh token JSON request
//
// swagger:model auth.refreshTokenJSONRequest
type AuthRefreshTokenJSONRequest struct {

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this auth refresh token JSON request
func (m *AuthRefreshTokenJSONRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth refresh token JSON request based on context it is used
func (m *AuthRefreshTokenJSONRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthRefreshTokenJSONRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthRefreshTokenJSONRequest) UnmarshalBinary(b []byte) error {
	var res AuthRefreshTokenJSONRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
