// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UimodelsMaintenanceStep uimodels maintenance step
//
// swagger:model uimodels.MaintenanceStep
type UimodelsMaintenanceStep struct {

	// description
	Description string `json:"description,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// planned time end
	// Format: date-time
	PlannedTimeEnd strfmt.DateTime `json:"planned_time_end,omitempty"`

	// planned time start
	// Format: date-time
	PlannedTimeStart strfmt.DateTime `json:"planned_time_start,omitempty"`

	// rollback description
	RollbackDescription string `json:"rollback_description,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this uimodels maintenance step
func (m *UimodelsMaintenanceStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlannedTimeEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlannedTimeStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UimodelsMaintenanceStep) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UimodelsMaintenanceStep) validatePlannedTimeEnd(formats strfmt.Registry) error {
	if swag.IsZero(m.PlannedTimeEnd) { // not required
		return nil
	}

	if err := validate.FormatOf("planned_time_end", "body", "date-time", m.PlannedTimeEnd.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UimodelsMaintenanceStep) validatePlannedTimeStart(formats strfmt.Registry) error {
	if swag.IsZero(m.PlannedTimeStart) { // not required
		return nil
	}

	if err := validate.FormatOf("planned_time_start", "body", "date-time", m.PlannedTimeStart.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this uimodels maintenance step based on context it is used
func (m *UimodelsMaintenanceStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UimodelsMaintenanceStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UimodelsMaintenanceStep) UnmarshalBinary(b []byte) error {
	var res UimodelsMaintenanceStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
