// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UimodelsMaintenanceViewResponse uimodels maintenance view response
//
// swagger:model uimodels.MaintenanceViewResponse
type UimodelsMaintenanceViewResponse struct {

	// actions
	Actions *UimodelsMaintenanceActions `json:"actions,omitempty"`

	// conflicts
	Conflicts []*UimodelsConflictView `json:"conflicts"`

	// maintenance
	Maintenance *UimodelsMaintenanceView `json:"maintenance,omitempty"`
}

// Validate validates this uimodels maintenance view response
func (m *UimodelsMaintenanceViewResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConflicts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaintenance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UimodelsMaintenanceViewResponse) validateActions(formats strfmt.Registry) error {
	if swag.IsZero(m.Actions) { // not required
		return nil
	}

	if m.Actions != nil {
		if err := m.Actions.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("actions")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("actions")
			}

			return err
		}
	}

	return nil
}

func (m *UimodelsMaintenanceViewResponse) validateConflicts(formats strfmt.Registry) error {
	if swag.IsZero(m.Conflicts) { // not required
		return nil
	}

	for i := 0; i < len(m.Conflicts); i++ {
		if swag.IsZero(m.Conflicts[i]) { // not required
			continue
		}

		if m.Conflicts[i] != nil {
			if err := m.Conflicts[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *UimodelsMaintenanceViewResponse) validateMaintenance(formats strfmt.Registry) error {
	if swag.IsZero(m.Maintenance) { // not required
		return nil
	}

	if m.Maintenance != nil {
		if err := m.Maintenance.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("maintenance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("maintenance")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this uimodels maintenance view response based on the context it is used
func (m *UimodelsMaintenanceViewResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConflicts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMaintenance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UimodelsMaintenanceViewResponse) contextValidateActions(ctx context.Context, formats strfmt.Registry) error {

	if m.Actions != nil {

		if swag.IsZero(m.Actions) { // not required
			return nil
		}

		if err := m.Actions.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("actions")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("actions")
			}

			return err
		}
	}

	return nil
}

func (m *UimodelsMaintenanceViewResponse) contextValidateConflicts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Conflicts); i++ {

		if m.Conflicts[i] != nil {

			if swag.IsZero(m.Conflicts[i]) { // not required
				return nil
			}

			if err := m.Conflicts[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *UimodelsMaintenanceViewResponse) contextValidateMaintenance(ctx context.Context, formats strfmt.Registry) error {

	if m.Maintenance != nil {

		if swag.IsZero(m.Maintenance) { // not required
			return nil
		}

		if err := m.Maintenance.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("maintenance")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("maintenance")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UimodelsMaintenanceViewResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UimodelsMaintenanceViewResponse) UnmarshalBinary(b []byte) error {
	var res UimodelsMaintenanceViewResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
