// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UimodelsMaintenanceStatus uimodels maintenance status
//
// swagger:model uimodels.MaintenanceStatus
type UimodelsMaintenanceStatus string

func NewUimodelsMaintenanceStatus(value UimodelsMaintenanceStatus) *UimodelsMaintenanceStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated UimodelsMaintenanceStatus.
func (m UimodelsMaintenanceStatus) Pointer() *UimodelsMaintenanceStatus {
	return &m
}

const (

	// UimodelsMaintenanceStatusDraft captures enum value "draft"
	UimodelsMaintenanceStatusDraft UimodelsMaintenanceStatus = "draft"

	// UimodelsMaintenanceStatusPlanned captures enum value "planned"
	UimodelsMaintenanceStatusPlanned UimodelsMaintenanceStatus = "planned"

	// UimodelsMaintenanceStatusInProgress captures enum value "in_progress"
	UimodelsMaintenanceStatusInProgress UimodelsMaintenanceStatus = "in_progress"

	// UimodelsMaintenanceStatusCanceled captures enum value "canceled"
	UimodelsMaintenanceStatusCanceled UimodelsMaintenanceStatus = "canceled"

	// UimodelsMaintenanceStatusCompleted captures enum value "completed"
	UimodelsMaintenanceStatusCompleted UimodelsMaintenanceStatus = "completed"
)

// for schema
var uimodelsMaintenanceStatusEnum []any

func init() {
	var res []UimodelsMaintenanceStatus
	if err := json.Unmarshal([]byte(`["draft","planned","in_progress","canceled","completed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		uimodelsMaintenanceStatusEnum = append(uimodelsMaintenanceStatusEnum, v)
	}
}

func (m UimodelsMaintenanceStatus) validateUimodelsMaintenanceStatusEnum(path, location string, value UimodelsMaintenanceStatus) error {
	if err := validate.EnumCase(path, location, value, uimodelsMaintenanceStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this uimodels maintenance status
func (m UimodelsMaintenanceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateUimodelsMaintenanceStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this uimodels maintenance status based on context it is used
func (m UimodelsMaintenanceStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
