environment: api_test

app:

logger:
  level: debug

api_server:
  name: api
  host: 0.0.0.0
  port: 8000

infra_server:
  name: status
  host: 0.0.0.0
  port: 8001

db:
  dsn: postgres://postgres:postgres@pg_doorman:6432/maintmode?sslmode=disable
  driver: postgres
  max_open_conns: 50
  max_idle_conns: 20
  connection_max_lifetime: 10m
  connection_max_idle_time: 5m

tracer:
  collector_host: otel-collector
  collector_port: 4317

redis:
  addr: redis:6379
  password: ""
  db: 0

external_services:
  auth:
    secret: maintmode-s2s-token
    protocol: http
    host: auth
    port: 8000

s2s:
