// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1ResourcesReader is a Reader for the GetAPIV1Resources structure.
type GetAPIV1ResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1ResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1ResourcesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1ResourcesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetAPIV1ResourcesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/resources] GetAPIV1Resources", response, response.Code())
	}
}

// NewGetAPIV1ResourcesOK creates a GetAPIV1ResourcesOK with default headers values
func NewGetAPIV1ResourcesOK() *GetAPIV1ResourcesOK {
	return &GetAPIV1ResourcesOK{}
}

/*
GetAPIV1ResourcesOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1ResourcesOK struct {
	Payload *models.ApimodelsSearchResourcesResponse
}

// IsSuccess returns true when this get Api v1 resources o k response has a 2xx status code
func (o *GetAPIV1ResourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 resources o k response has a 3xx status code
func (o *GetAPIV1ResourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources o k response has a 4xx status code
func (o *GetAPIV1ResourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 resources o k response has a 5xx status code
func (o *GetAPIV1ResourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 resources o k response a status code equal to that given
func (o *GetAPIV1ResourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 resources o k response
func (o *GetAPIV1ResourcesOK) Code() int {
	return 200
}

func (o *GetAPIV1ResourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesOK %s", 200, payload)
}

func (o *GetAPIV1ResourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesOK %s", 200, payload)
}

func (o *GetAPIV1ResourcesOK) GetPayload() *models.ApimodelsSearchResourcesResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApimodelsSearchResourcesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1ResourcesBadRequest creates a GetAPIV1ResourcesBadRequest with default headers values
func NewGetAPIV1ResourcesBadRequest() *GetAPIV1ResourcesBadRequest {
	return &GetAPIV1ResourcesBadRequest{}
}

/*
GetAPIV1ResourcesBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type GetAPIV1ResourcesBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 resources bad request response has a 2xx status code
func (o *GetAPIV1ResourcesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 resources bad request response has a 3xx status code
func (o *GetAPIV1ResourcesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources bad request response has a 4xx status code
func (o *GetAPIV1ResourcesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 resources bad request response has a 5xx status code
func (o *GetAPIV1ResourcesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 resources bad request response a status code equal to that given
func (o *GetAPIV1ResourcesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 resources bad request response
func (o *GetAPIV1ResourcesBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1ResourcesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesBadRequest %s", 400, payload)
}

func (o *GetAPIV1ResourcesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesBadRequest %s", 400, payload)
}

func (o *GetAPIV1ResourcesBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1ResourcesUnauthorized creates a GetAPIV1ResourcesUnauthorized with default headers values
func NewGetAPIV1ResourcesUnauthorized() *GetAPIV1ResourcesUnauthorized {
	return &GetAPIV1ResourcesUnauthorized{}
}

/*
GetAPIV1ResourcesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1ResourcesUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 resources unauthorized response has a 2xx status code
func (o *GetAPIV1ResourcesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 resources unauthorized response has a 3xx status code
func (o *GetAPIV1ResourcesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources unauthorized response has a 4xx status code
func (o *GetAPIV1ResourcesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 resources unauthorized response has a 5xx status code
func (o *GetAPIV1ResourcesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 resources unauthorized response a status code equal to that given
func (o *GetAPIV1ResourcesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 resources unauthorized response
func (o *GetAPIV1ResourcesUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1ResourcesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ResourcesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ResourcesUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1ResourcesForbidden creates a GetAPIV1ResourcesForbidden with default headers values
func NewGetAPIV1ResourcesForbidden() *GetAPIV1ResourcesForbidden {
	return &GetAPIV1ResourcesForbidden{}
}

/*
GetAPIV1ResourcesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1ResourcesForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 resources forbidden response has a 2xx status code
func (o *GetAPIV1ResourcesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 resources forbidden response has a 3xx status code
func (o *GetAPIV1ResourcesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources forbidden response has a 4xx status code
func (o *GetAPIV1ResourcesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 resources forbidden response has a 5xx status code
func (o *GetAPIV1ResourcesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 resources forbidden response a status code equal to that given
func (o *GetAPIV1ResourcesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 resources forbidden response
func (o *GetAPIV1ResourcesForbidden) Code() int {
	return 403
}

func (o *GetAPIV1ResourcesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesForbidden %s", 403, payload)
}

func (o *GetAPIV1ResourcesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesForbidden %s", 403, payload)
}

func (o *GetAPIV1ResourcesForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1ResourcesInternalServerError creates a GetAPIV1ResourcesInternalServerError with default headers values
func NewGetAPIV1ResourcesInternalServerError() *GetAPIV1ResourcesInternalServerError {
	return &GetAPIV1ResourcesInternalServerError{}
}

/*
GetAPIV1ResourcesInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAPIV1ResourcesInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 resources internal server error response has a 2xx status code
func (o *GetAPIV1ResourcesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 resources internal server error response has a 3xx status code
func (o *GetAPIV1ResourcesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources internal server error response has a 4xx status code
func (o *GetAPIV1ResourcesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 resources internal server error response has a 5xx status code
func (o *GetAPIV1ResourcesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 resources internal server error response a status code equal to that given
func (o *GetAPIV1ResourcesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 resources internal server error response
func (o *GetAPIV1ResourcesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ResourcesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ResourcesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ResourcesInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1ResourcesServiceUnavailable creates a GetAPIV1ResourcesServiceUnavailable with default headers values
func NewGetAPIV1ResourcesServiceUnavailable() *GetAPIV1ResourcesServiceUnavailable {
	return &GetAPIV1ResourcesServiceUnavailable{}
}

/*
GetAPIV1ResourcesServiceUnavailable describes a response with status code 503, with default header values.

Auth service unavailable
*/
type GetAPIV1ResourcesServiceUnavailable struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 resources service unavailable response has a 2xx status code
func (o *GetAPIV1ResourcesServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 resources service unavailable response has a 3xx status code
func (o *GetAPIV1ResourcesServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 resources service unavailable response has a 4xx status code
func (o *GetAPIV1ResourcesServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 resources service unavailable response has a 5xx status code
func (o *GetAPIV1ResourcesServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 resources service unavailable response a status code equal to that given
func (o *GetAPIV1ResourcesServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get Api v1 resources service unavailable response
func (o *GetAPIV1ResourcesServiceUnavailable) Code() int {
	return 503
}

func (o *GetAPIV1ResourcesServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1ResourcesServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/resources][%d] getApiV1ResourcesServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1ResourcesServiceUnavailable) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ResourcesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
