// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// NewPatchAPIV1ResourceIDParams creates a new PatchAPIV1ResourceIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIV1ResourceIDParams() *PatchAPIV1ResourceIDParams {
	return &PatchAPIV1ResourceIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV1ResourceIDParamsWithTimeout creates a new PatchAPIV1ResourceIDParams object
// with the ability to set a timeout on a request.
func NewPatchAPIV1ResourceIDParamsWithTimeout(timeout time.Duration) *PatchAPIV1ResourceIDParams {
	return &PatchAPIV1ResourceIDParams{
		timeout: timeout,
	}
}

// NewPatchAPIV1ResourceIDParamsWithContext creates a new PatchAPIV1ResourceIDParams object
// with the ability to set a context for a request.
func NewPatchAPIV1ResourceIDParamsWithContext(ctx context.Context) *PatchAPIV1ResourceIDParams {
	return &PatchAPIV1ResourceIDParams{
		Context: ctx,
	}
}

// NewPatchAPIV1ResourceIDParamsWithHTTPClient creates a new PatchAPIV1ResourceIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIV1ResourceIDParamsWithHTTPClient(client *http.Client) *PatchAPIV1ResourceIDParams {
	return &PatchAPIV1ResourceIDParams{
		HTTPClient: client,
	}
}

/*
PatchAPIV1ResourceIDParams contains all the parameters to send to the API endpoint

	for the patch API v1 resource ID operation.

	Typically these are written to a http.Request.
*/
type PatchAPIV1ResourceIDParams struct {

	/* ID.

	   Resource ID

	   Format: uuid
	*/
	ID strfmt.UUID

	/* Request.

	   Fields to update
	*/
	Request *models.ApimodelsUpdateResourceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API v1 resource ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV1ResourceIDParams) WithDefaults() *PatchAPIV1ResourceIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API v1 resource ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV1ResourceIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) WithTimeout(timeout time.Duration) *PatchAPIV1ResourceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) WithContext(ctx context.Context) *PatchAPIV1ResourceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) WithHTTPClient(client *http.Client) *PatchAPIV1ResourceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) WithID(id strfmt.UUID) *PatchAPIV1ResourceIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithRequest adds the request to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) WithRequest(request *models.ApimodelsUpdateResourceRequest) *PatchAPIV1ResourceIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the patch API v1 resource ID params
func (o *PatchAPIV1ResourceIDParams) SetRequest(request *models.ApimodelsUpdateResourceRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV1ResourceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
