// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PatchAPIV1ResourceIDReader is a Reader for the PatchAPIV1ResourceID structure.
type PatchAPIV1ResourceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIV1ResourceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIV1ResourceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchAPIV1ResourceIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchAPIV1ResourceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPatchAPIV1ResourceIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchAPIV1ResourceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPatchAPIV1ResourceIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchAPIV1ResourceIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPatchAPIV1ResourceIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /api/v1/resource/{id}] PatchAPIV1ResourceID", response, response.Code())
	}
}

// NewPatchAPIV1ResourceIDOK creates a PatchAPIV1ResourceIDOK with default headers values
func NewPatchAPIV1ResourceIDOK() *PatchAPIV1ResourceIDOK {
	return &PatchAPIV1ResourceIDOK{}
}

/*
PatchAPIV1ResourceIDOK describes a response with status code 200, with default header values.

OK
*/
type PatchAPIV1ResourceIDOK struct {
	Payload *models.ApimodelsResource
}

// IsSuccess returns true when this patch Api v1 resource Id o k response has a 2xx status code
func (o *PatchAPIV1ResourceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api v1 resource Id o k response has a 3xx status code
func (o *PatchAPIV1ResourceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id o k response has a 4xx status code
func (o *PatchAPIV1ResourceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api v1 resource Id o k response has a 5xx status code
func (o *PatchAPIV1ResourceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id o k response a status code equal to that given
func (o *PatchAPIV1ResourceIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch Api v1 resource Id o k response
func (o *PatchAPIV1ResourceIDOK) Code() int {
	return 200
}

func (o *PatchAPIV1ResourceIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdOK %s", 200, payload)
}

func (o *PatchAPIV1ResourceIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdOK %s", 200, payload)
}

func (o *PatchAPIV1ResourceIDOK) GetPayload() *models.ApimodelsResource {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApimodelsResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDBadRequest creates a PatchAPIV1ResourceIDBadRequest with default headers values
func NewPatchAPIV1ResourceIDBadRequest() *PatchAPIV1ResourceIDBadRequest {
	return &PatchAPIV1ResourceIDBadRequest{}
}

/*
PatchAPIV1ResourceIDBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type PatchAPIV1ResourceIDBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id bad request response has a 2xx status code
func (o *PatchAPIV1ResourceIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id bad request response has a 3xx status code
func (o *PatchAPIV1ResourceIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id bad request response has a 4xx status code
func (o *PatchAPIV1ResourceIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch Api v1 resource Id bad request response has a 5xx status code
func (o *PatchAPIV1ResourceIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id bad request response a status code equal to that given
func (o *PatchAPIV1ResourceIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch Api v1 resource Id bad request response
func (o *PatchAPIV1ResourceIDBadRequest) Code() int {
	return 400
}

func (o *PatchAPIV1ResourceIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdBadRequest %s", 400, payload)
}

func (o *PatchAPIV1ResourceIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdBadRequest %s", 400, payload)
}

func (o *PatchAPIV1ResourceIDBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDUnauthorized creates a PatchAPIV1ResourceIDUnauthorized with default headers values
func NewPatchAPIV1ResourceIDUnauthorized() *PatchAPIV1ResourceIDUnauthorized {
	return &PatchAPIV1ResourceIDUnauthorized{}
}

/*
PatchAPIV1ResourceIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PatchAPIV1ResourceIDUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id unauthorized response has a 2xx status code
func (o *PatchAPIV1ResourceIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id unauthorized response has a 3xx status code
func (o *PatchAPIV1ResourceIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id unauthorized response has a 4xx status code
func (o *PatchAPIV1ResourceIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch Api v1 resource Id unauthorized response has a 5xx status code
func (o *PatchAPIV1ResourceIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id unauthorized response a status code equal to that given
func (o *PatchAPIV1ResourceIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the patch Api v1 resource Id unauthorized response
func (o *PatchAPIV1ResourceIDUnauthorized) Code() int {
	return 401
}

func (o *PatchAPIV1ResourceIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdUnauthorized %s", 401, payload)
}

func (o *PatchAPIV1ResourceIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdUnauthorized %s", 401, payload)
}

func (o *PatchAPIV1ResourceIDUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDForbidden creates a PatchAPIV1ResourceIDForbidden with default headers values
func NewPatchAPIV1ResourceIDForbidden() *PatchAPIV1ResourceIDForbidden {
	return &PatchAPIV1ResourceIDForbidden{}
}

/*
PatchAPIV1ResourceIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PatchAPIV1ResourceIDForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id forbidden response has a 2xx status code
func (o *PatchAPIV1ResourceIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id forbidden response has a 3xx status code
func (o *PatchAPIV1ResourceIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id forbidden response has a 4xx status code
func (o *PatchAPIV1ResourceIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch Api v1 resource Id forbidden response has a 5xx status code
func (o *PatchAPIV1ResourceIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id forbidden response a status code equal to that given
func (o *PatchAPIV1ResourceIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the patch Api v1 resource Id forbidden response
func (o *PatchAPIV1ResourceIDForbidden) Code() int {
	return 403
}

func (o *PatchAPIV1ResourceIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdForbidden %s", 403, payload)
}

func (o *PatchAPIV1ResourceIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdForbidden %s", 403, payload)
}

func (o *PatchAPIV1ResourceIDForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDNotFound creates a PatchAPIV1ResourceIDNotFound with default headers values
func NewPatchAPIV1ResourceIDNotFound() *PatchAPIV1ResourceIDNotFound {
	return &PatchAPIV1ResourceIDNotFound{}
}

/*
PatchAPIV1ResourceIDNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type PatchAPIV1ResourceIDNotFound struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id not found response has a 2xx status code
func (o *PatchAPIV1ResourceIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id not found response has a 3xx status code
func (o *PatchAPIV1ResourceIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id not found response has a 4xx status code
func (o *PatchAPIV1ResourceIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch Api v1 resource Id not found response has a 5xx status code
func (o *PatchAPIV1ResourceIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id not found response a status code equal to that given
func (o *PatchAPIV1ResourceIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the patch Api v1 resource Id not found response
func (o *PatchAPIV1ResourceIDNotFound) Code() int {
	return 404
}

func (o *PatchAPIV1ResourceIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdNotFound %s", 404, payload)
}

func (o *PatchAPIV1ResourceIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdNotFound %s", 404, payload)
}

func (o *PatchAPIV1ResourceIDNotFound) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDConflict creates a PatchAPIV1ResourceIDConflict with default headers values
func NewPatchAPIV1ResourceIDConflict() *PatchAPIV1ResourceIDConflict {
	return &PatchAPIV1ResourceIDConflict{}
}

/*
PatchAPIV1ResourceIDConflict describes a response with status code 409, with default header values.

Resource name already exists
*/
type PatchAPIV1ResourceIDConflict struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id conflict response has a 2xx status code
func (o *PatchAPIV1ResourceIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id conflict response has a 3xx status code
func (o *PatchAPIV1ResourceIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id conflict response has a 4xx status code
func (o *PatchAPIV1ResourceIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch Api v1 resource Id conflict response has a 5xx status code
func (o *PatchAPIV1ResourceIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v1 resource Id conflict response a status code equal to that given
func (o *PatchAPIV1ResourceIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the patch Api v1 resource Id conflict response
func (o *PatchAPIV1ResourceIDConflict) Code() int {
	return 409
}

func (o *PatchAPIV1ResourceIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdConflict %s", 409, payload)
}

func (o *PatchAPIV1ResourceIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdConflict %s", 409, payload)
}

func (o *PatchAPIV1ResourceIDConflict) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDInternalServerError creates a PatchAPIV1ResourceIDInternalServerError with default headers values
func NewPatchAPIV1ResourceIDInternalServerError() *PatchAPIV1ResourceIDInternalServerError {
	return &PatchAPIV1ResourceIDInternalServerError{}
}

/*
PatchAPIV1ResourceIDInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PatchAPIV1ResourceIDInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id internal server error response has a 2xx status code
func (o *PatchAPIV1ResourceIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id internal server error response has a 3xx status code
func (o *PatchAPIV1ResourceIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id internal server error response has a 4xx status code
func (o *PatchAPIV1ResourceIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api v1 resource Id internal server error response has a 5xx status code
func (o *PatchAPIV1ResourceIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this patch Api v1 resource Id internal server error response a status code equal to that given
func (o *PatchAPIV1ResourceIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the patch Api v1 resource Id internal server error response
func (o *PatchAPIV1ResourceIDInternalServerError) Code() int {
	return 500
}

func (o *PatchAPIV1ResourceIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdInternalServerError %s", 500, payload)
}

func (o *PatchAPIV1ResourceIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdInternalServerError %s", 500, payload)
}

func (o *PatchAPIV1ResourceIDInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchAPIV1ResourceIDServiceUnavailable creates a PatchAPIV1ResourceIDServiceUnavailable with default headers values
func NewPatchAPIV1ResourceIDServiceUnavailable() *PatchAPIV1ResourceIDServiceUnavailable {
	return &PatchAPIV1ResourceIDServiceUnavailable{}
}

/*
PatchAPIV1ResourceIDServiceUnavailable describes a response with status code 503, with default header values.

Auth service unavailable
*/
type PatchAPIV1ResourceIDServiceUnavailable struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this patch Api v1 resource Id service unavailable response has a 2xx status code
func (o *PatchAPIV1ResourceIDServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch Api v1 resource Id service unavailable response has a 3xx status code
func (o *PatchAPIV1ResourceIDServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v1 resource Id service unavailable response has a 4xx status code
func (o *PatchAPIV1ResourceIDServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api v1 resource Id service unavailable response has a 5xx status code
func (o *PatchAPIV1ResourceIDServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this patch Api v1 resource Id service unavailable response a status code equal to that given
func (o *PatchAPIV1ResourceIDServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the patch Api v1 resource Id service unavailable response
func (o *PatchAPIV1ResourceIDServiceUnavailable) Code() int {
	return 503
}

func (o *PatchAPIV1ResourceIDServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdServiceUnavailable %s", 503, payload)
}

func (o *PatchAPIV1ResourceIDServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v1/resource/{id}][%d] patchApiV1ResourceIdServiceUnavailable %s", 503, payload)
}

func (o *PatchAPIV1ResourceIDServiceUnavailable) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PatchAPIV1ResourceIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
