// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAPIV1ResourceIDArchiveReader is a Reader for the PostAPIV1ResourceIDArchive structure.
type PostAPIV1ResourceIDArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1ResourceIDArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostAPIV1ResourceIDArchiveNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1ResourceIDArchiveBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1ResourceIDArchiveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1ResourceIDArchiveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1ResourceIDArchiveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostAPIV1ResourceIDArchiveServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/resource/{id}/archive] PostAPIV1ResourceIDArchive", response, response.Code())
	}
}

// NewPostAPIV1ResourceIDArchiveNoContent creates a PostAPIV1ResourceIDArchiveNoContent with default headers values
func NewPostAPIV1ResourceIDArchiveNoContent() *PostAPIV1ResourceIDArchiveNoContent {
	return &PostAPIV1ResourceIDArchiveNoContent{}
}

/*
PostAPIV1ResourceIDArchiveNoContent describes a response with status code 204, with default header values.

Resource archived
*/
type PostAPIV1ResourceIDArchiveNoContent struct {
}

// IsSuccess returns true when this post Api v1 resource Id archive no content response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 resource Id archive no content response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive no content response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 resource Id archive no content response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 resource Id archive no content response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post Api v1 resource Id archive no content response
func (o *PostAPIV1ResourceIDArchiveNoContent) Code() int {
	return 204
}

func (o *PostAPIV1ResourceIDArchiveNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveNoContent", 204)
}

func (o *PostAPIV1ResourceIDArchiveNoContent) String() string {
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveNoContent", 204)
}

func (o *PostAPIV1ResourceIDArchiveNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1ResourceIDArchiveBadRequest creates a PostAPIV1ResourceIDArchiveBadRequest with default headers values
func NewPostAPIV1ResourceIDArchiveBadRequest() *PostAPIV1ResourceIDArchiveBadRequest {
	return &PostAPIV1ResourceIDArchiveBadRequest{}
}

/*
PostAPIV1ResourceIDArchiveBadRequest describes a response with status code 400, with default header values.

Invalid resource id
*/
type PostAPIV1ResourceIDArchiveBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 resource Id archive bad request response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 resource Id archive bad request response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive bad request response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 resource Id archive bad request response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 resource Id archive bad request response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 resource Id archive bad request response
func (o *PostAPIV1ResourceIDArchiveBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1ResourceIDArchiveBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveBadRequest %s", 400, payload)
}

func (o *PostAPIV1ResourceIDArchiveBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveBadRequest %s", 400, payload)
}

func (o *PostAPIV1ResourceIDArchiveBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ResourceIDArchiveBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1ResourceIDArchiveUnauthorized creates a PostAPIV1ResourceIDArchiveUnauthorized with default headers values
func NewPostAPIV1ResourceIDArchiveUnauthorized() *PostAPIV1ResourceIDArchiveUnauthorized {
	return &PostAPIV1ResourceIDArchiveUnauthorized{}
}

/*
PostAPIV1ResourceIDArchiveUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1ResourceIDArchiveUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 resource Id archive unauthorized response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 resource Id archive unauthorized response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive unauthorized response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 resource Id archive unauthorized response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 resource Id archive unauthorized response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 resource Id archive unauthorized response
func (o *PostAPIV1ResourceIDArchiveUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1ResourceIDArchiveUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ResourceIDArchiveUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ResourceIDArchiveUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ResourceIDArchiveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1ResourceIDArchiveForbidden creates a PostAPIV1ResourceIDArchiveForbidden with default headers values
func NewPostAPIV1ResourceIDArchiveForbidden() *PostAPIV1ResourceIDArchiveForbidden {
	return &PostAPIV1ResourceIDArchiveForbidden{}
}

/*
PostAPIV1ResourceIDArchiveForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIV1ResourceIDArchiveForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 resource Id archive forbidden response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 resource Id archive forbidden response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive forbidden response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 resource Id archive forbidden response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 resource Id archive forbidden response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 resource Id archive forbidden response
func (o *PostAPIV1ResourceIDArchiveForbidden) Code() int {
	return 403
}

func (o *PostAPIV1ResourceIDArchiveForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveForbidden %s", 403, payload)
}

func (o *PostAPIV1ResourceIDArchiveForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveForbidden %s", 403, payload)
}

func (o *PostAPIV1ResourceIDArchiveForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ResourceIDArchiveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1ResourceIDArchiveInternalServerError creates a PostAPIV1ResourceIDArchiveInternalServerError with default headers values
func NewPostAPIV1ResourceIDArchiveInternalServerError() *PostAPIV1ResourceIDArchiveInternalServerError {
	return &PostAPIV1ResourceIDArchiveInternalServerError{}
}

/*
PostAPIV1ResourceIDArchiveInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPIV1ResourceIDArchiveInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 resource Id archive internal server error response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 resource Id archive internal server error response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive internal server error response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 resource Id archive internal server error response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 resource Id archive internal server error response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 resource Id archive internal server error response
func (o *PostAPIV1ResourceIDArchiveInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1ResourceIDArchiveInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ResourceIDArchiveInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ResourceIDArchiveInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ResourceIDArchiveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1ResourceIDArchiveServiceUnavailable creates a PostAPIV1ResourceIDArchiveServiceUnavailable with default headers values
func NewPostAPIV1ResourceIDArchiveServiceUnavailable() *PostAPIV1ResourceIDArchiveServiceUnavailable {
	return &PostAPIV1ResourceIDArchiveServiceUnavailable{}
}

/*
PostAPIV1ResourceIDArchiveServiceUnavailable describes a response with status code 503, with default header values.

Auth service unavailable
*/
type PostAPIV1ResourceIDArchiveServiceUnavailable struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 resource Id archive service unavailable response has a 2xx status code
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 resource Id archive service unavailable response has a 3xx status code
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 resource Id archive service unavailable response has a 4xx status code
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 resource Id archive service unavailable response has a 5xx status code
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 resource Id archive service unavailable response a status code equal to that given
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the post Api v1 resource Id archive service unavailable response
func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) Code() int {
	return 503
}

func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveServiceUnavailable %s", 503, payload)
}

func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/resource/{id}/archive][%d] postApiV1ResourceIdArchiveServiceUnavailable %s", 503, payload)
}

func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ResourceIDArchiveServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
