// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1ResourceIDUnarchiveParams creates a new PostAPIV1ResourceIDUnarchiveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1ResourceIDUnarchiveParams() *PostAPIV1ResourceIDUnarchiveParams {
	return &PostAPIV1ResourceIDUnarchiveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1ResourceIDUnarchiveParamsWithTimeout creates a new PostAPIV1ResourceIDUnarchiveParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1ResourceIDUnarchiveParamsWithTimeout(timeout time.Duration) *PostAPIV1ResourceIDUnarchiveParams {
	return &PostAPIV1ResourceIDUnarchiveParams{
		timeout: timeout,
	}
}

// NewPostAPIV1ResourceIDUnarchiveParamsWithContext creates a new PostAPIV1ResourceIDUnarchiveParams object
// with the ability to set a context for a request.
func NewPostAPIV1ResourceIDUnarchiveParamsWithContext(ctx context.Context) *PostAPIV1ResourceIDUnarchiveParams {
	return &PostAPIV1ResourceIDUnarchiveParams{
		Context: ctx,
	}
}

// NewPostAPIV1ResourceIDUnarchiveParamsWithHTTPClient creates a new PostAPIV1ResourceIDUnarchiveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1ResourceIDUnarchiveParamsWithHTTPClient(client *http.Client) *PostAPIV1ResourceIDUnarchiveParams {
	return &PostAPIV1ResourceIDUnarchiveParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1ResourceIDUnarchiveParams contains all the parameters to send to the API endpoint

	for the post API v1 resource ID unarchive operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1ResourceIDUnarchiveParams struct {

	/* ID.

	   Resource ID

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 resource ID unarchive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ResourceIDUnarchiveParams) WithDefaults() *PostAPIV1ResourceIDUnarchiveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 resource ID unarchive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ResourceIDUnarchiveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) WithTimeout(timeout time.Duration) *PostAPIV1ResourceIDUnarchiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) WithContext(ctx context.Context) *PostAPIV1ResourceIDUnarchiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) WithHTTPClient(client *http.Client) *PostAPIV1ResourceIDUnarchiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) WithID(id strfmt.UUID) *PostAPIV1ResourceIDUnarchiveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post API v1 resource ID unarchive params
func (o *PostAPIV1ResourceIDUnarchiveParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1ResourceIDUnarchiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
