environment: local

app:
  frontend_url: http://localhost:8000

rbac:
  adapter: file
  model_path: deployment/auth/authz/model.conf
  policy_path: deployment/auth/authz/policy.csv

logger:
  level: debug

api_server:
  name: api
  host: 0.0.0.0
  port: 8000

infra_server:
  name: status
  host: 0.0.0.0
  port: 8001

db:
  dsn: <secret:db/dsn>
  driver: postgres
  max_open_conns: 50
  max_idle_conns: 20
  connection_max_lifetime: 10m
  connection_max_idle_time: 5m

tracer:
  collector_host: otel-collector
  collector_port: 4317

redis:
  addr: localhost:6379
  password: <secret:redis/password>
  db: 0

oauth_providers:
  stub:
    redirect_url: http://localhost:9000/auth/api/v1/login/oauth/google/callback
  google:
    client_id: <secret:oauth/google/client_id>
    client_secret: <secret:oauth/google/client_secret>
    redirect_url: http://localhost:9000/auth/api/v1/login/oauth/google/callback
    google_userinfo_url: https://www.googleapis.com/oauth2/v2/userinfo
    scopes:
      - "openid"
      - "email"
      - "profile"

jwt:
  issuer_name: oauth-service
  issuer_private_key: <secret:jwt/issuer_private_key>
  issuer_kid: <secret:jwt/issuer_kid>
  access_token_ttl: 15m
  refresh_token_ttl: 720h # 30 days
  refresh_token_grace_period: 1ms
  refresh_token_distributed_lock_ttl: 5s

external_services:

s2s:
  maintmode:
    secret: <secret:s2s/maintmode/secret>
    available_api:
      - /api/v1/s2s/introspect
  testauth:
    secret: <secret:s2s/testauth/secret>
    available_api:
      - /api/v1/s2s/introspect
