// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1MeReader is a Reader for the GetAPIV1Me structure.
type GetAPIV1MeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1MeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1MeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1MeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1MeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/me] GetAPIV1Me", response, response.Code())
	}
}

// NewGetAPIV1MeOK creates a GetAPIV1MeOK with default headers values
func NewGetAPIV1MeOK() *GetAPIV1MeOK {
	return &GetAPIV1MeOK{}
}

/*
GetAPIV1MeOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1MeOK struct {
	Payload *models.ApiauthmodelsMeResponse
}

// IsSuccess returns true when this get Api v1 me o k response has a 2xx status code
func (o *GetAPIV1MeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 me o k response has a 3xx status code
func (o *GetAPIV1MeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 me o k response has a 4xx status code
func (o *GetAPIV1MeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 me o k response has a 5xx status code
func (o *GetAPIV1MeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 me o k response a status code equal to that given
func (o *GetAPIV1MeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 me o k response
func (o *GetAPIV1MeOK) Code() int {
	return 200
}

func (o *GetAPIV1MeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeOK %s", 200, payload)
}

func (o *GetAPIV1MeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeOK %s", 200, payload)
}

func (o *GetAPIV1MeOK) GetPayload() *models.ApiauthmodelsMeResponse {
	return o.Payload
}

func (o *GetAPIV1MeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiauthmodelsMeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1MeUnauthorized creates a GetAPIV1MeUnauthorized with default headers values
func NewGetAPIV1MeUnauthorized() *GetAPIV1MeUnauthorized {
	return &GetAPIV1MeUnauthorized{}
}

/*
GetAPIV1MeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1MeUnauthorized struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 me unauthorized response has a 2xx status code
func (o *GetAPIV1MeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 me unauthorized response has a 3xx status code
func (o *GetAPIV1MeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 me unauthorized response has a 4xx status code
func (o *GetAPIV1MeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 me unauthorized response has a 5xx status code
func (o *GetAPIV1MeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 me unauthorized response a status code equal to that given
func (o *GetAPIV1MeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 me unauthorized response
func (o *GetAPIV1MeUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1MeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeUnauthorized %s", 401, payload)
}

func (o *GetAPIV1MeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeUnauthorized %s", 401, payload)
}

func (o *GetAPIV1MeUnauthorized) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1MeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1MeInternalServerError creates a GetAPIV1MeInternalServerError with default headers values
func NewGetAPIV1MeInternalServerError() *GetAPIV1MeInternalServerError {
	return &GetAPIV1MeInternalServerError{}
}

/*
GetAPIV1MeInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAPIV1MeInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 me internal server error response has a 2xx status code
func (o *GetAPIV1MeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 me internal server error response has a 3xx status code
func (o *GetAPIV1MeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 me internal server error response has a 4xx status code
func (o *GetAPIV1MeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 me internal server error response has a 5xx status code
func (o *GetAPIV1MeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 me internal server error response a status code equal to that given
func (o *GetAPIV1MeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 me internal server error response
func (o *GetAPIV1MeInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1MeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeInternalServerError %s", 500, payload)
}

func (o *GetAPIV1MeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/me][%d] getApiV1MeInternalServerError %s", 500, payload)
}

func (o *GetAPIV1MeInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1MeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
