// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAuthV1LoginOauthGoogleReader is a Reader for the GetAuthV1LoginOauthGoogle structure.
type GetAuthV1LoginOauthGoogleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthV1LoginOauthGoogleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 307:
		result := NewGetAuthV1LoginOauthGoogleTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAuthV1LoginOauthGoogleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /auth/v1/login/oauth/google] GetAuthV1LoginOauthGoogle", response, response.Code())
	}
}

// NewGetAuthV1LoginOauthGoogleTemporaryRedirect creates a GetAuthV1LoginOauthGoogleTemporaryRedirect with default headers values
func NewGetAuthV1LoginOauthGoogleTemporaryRedirect() *GetAuthV1LoginOauthGoogleTemporaryRedirect {
	return &GetAuthV1LoginOauthGoogleTemporaryRedirect{}
}

/*
GetAuthV1LoginOauthGoogleTemporaryRedirect describes a response with status code 307, with default header values.

Temporary redirect to OAuth provider
*/
type GetAuthV1LoginOauthGoogleTemporaryRedirect struct {
}

// IsSuccess returns true when this get auth v1 login oauth google temporary redirect response has a 2xx status code
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth v1 login oauth google temporary redirect response has a 3xx status code
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) IsRedirect() bool {
	return true
}

// IsClientError returns true when this get auth v1 login oauth google temporary redirect response has a 4xx status code
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth v1 login oauth google temporary redirect response has a 5xx status code
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth v1 login oauth google temporary redirect response a status code equal to that given
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) IsCode(code int) bool {
	return code == 307
}

// Code gets the status code for the get auth v1 login oauth google temporary redirect response
func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) Code() int {
	return 307
}

func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) Error() string {
	return fmt.Sprintf("[GET /auth/v1/login/oauth/google][%d] getAuthV1LoginOauthGoogleTemporaryRedirect", 307)
}

func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) String() string {
	return fmt.Sprintf("[GET /auth/v1/login/oauth/google][%d] getAuthV1LoginOauthGoogleTemporaryRedirect", 307)
}

func (o *GetAuthV1LoginOauthGoogleTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAuthV1LoginOauthGoogleInternalServerError creates a GetAuthV1LoginOauthGoogleInternalServerError with default headers values
func NewGetAuthV1LoginOauthGoogleInternalServerError() *GetAuthV1LoginOauthGoogleInternalServerError {
	return &GetAuthV1LoginOauthGoogleInternalServerError{}
}

/*
GetAuthV1LoginOauthGoogleInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAuthV1LoginOauthGoogleInternalServerError struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this get auth v1 login oauth google internal server error response has a 2xx status code
func (o *GetAuthV1LoginOauthGoogleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth v1 login oauth google internal server error response has a 3xx status code
func (o *GetAuthV1LoginOauthGoogleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth v1 login oauth google internal server error response has a 4xx status code
func (o *GetAuthV1LoginOauthGoogleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth v1 login oauth google internal server error response has a 5xx status code
func (o *GetAuthV1LoginOauthGoogleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get auth v1 login oauth google internal server error response a status code equal to that given
func (o *GetAuthV1LoginOauthGoogleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get auth v1 login oauth google internal server error response
func (o *GetAuthV1LoginOauthGoogleInternalServerError) Code() int {
	return 500
}

func (o *GetAuthV1LoginOauthGoogleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/v1/login/oauth/google][%d] getAuthV1LoginOauthGoogleInternalServerError %s", 500, payload)
}

func (o *GetAuthV1LoginOauthGoogleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/v1/login/oauth/google][%d] getAuthV1LoginOauthGoogleInternalServerError %s", 500, payload)
}

func (o *GetAuthV1LoginOauthGoogleInternalServerError) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *GetAuthV1LoginOauthGoogleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
