// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1LoginOauthGoogleReader is a Reader for the GetAPIV1LoginOauthGoogle structure.
type GetAPIV1LoginOauthGoogleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1LoginOauthGoogleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 307:
		result := NewGetAPIV1LoginOauthGoogleTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1LoginOauthGoogleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/login/oauth/google] GetAPIV1LoginOauthGoogle", response, response.Code())
	}
}

// NewGetAPIV1LoginOauthGoogleTemporaryRedirect creates a GetAPIV1LoginOauthGoogleTemporaryRedirect with default headers values
func NewGetAPIV1LoginOauthGoogleTemporaryRedirect() *GetAPIV1LoginOauthGoogleTemporaryRedirect {
	return &GetAPIV1LoginOauthGoogleTemporaryRedirect{}
}

/*
GetAPIV1LoginOauthGoogleTemporaryRedirect describes a response with status code 307, with default header values.

Temporary redirect to OAuth provider
*/
type GetAPIV1LoginOauthGoogleTemporaryRedirect struct {
}

// IsSuccess returns true when this get Api v1 login oauth google temporary redirect response has a 2xx status code
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 login oauth google temporary redirect response has a 3xx status code
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) IsRedirect() bool {
	return true
}

// IsClientError returns true when this get Api v1 login oauth google temporary redirect response has a 4xx status code
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 login oauth google temporary redirect response has a 5xx status code
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 login oauth google temporary redirect response a status code equal to that given
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) IsCode(code int) bool {
	return code == 307
}

// Code gets the status code for the get Api v1 login oauth google temporary redirect response
func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) Code() int {
	return 307
}

func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) Error() string {
	return fmt.Sprintf("[GET /api/v1/login/oauth/google][%d] getApiV1LoginOauthGoogleTemporaryRedirect", 307)
}

func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) String() string {
	return fmt.Sprintf("[GET /api/v1/login/oauth/google][%d] getApiV1LoginOauthGoogleTemporaryRedirect", 307)
}

func (o *GetAPIV1LoginOauthGoogleTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1LoginOauthGoogleInternalServerError creates a GetAPIV1LoginOauthGoogleInternalServerError with default headers values
func NewGetAPIV1LoginOauthGoogleInternalServerError() *GetAPIV1LoginOauthGoogleInternalServerError {
	return &GetAPIV1LoginOauthGoogleInternalServerError{}
}

/*
GetAPIV1LoginOauthGoogleInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAPIV1LoginOauthGoogleInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 login oauth google internal server error response has a 2xx status code
func (o *GetAPIV1LoginOauthGoogleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 login oauth google internal server error response has a 3xx status code
func (o *GetAPIV1LoginOauthGoogleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 login oauth google internal server error response has a 4xx status code
func (o *GetAPIV1LoginOauthGoogleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 login oauth google internal server error response has a 5xx status code
func (o *GetAPIV1LoginOauthGoogleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 login oauth google internal server error response a status code equal to that given
func (o *GetAPIV1LoginOauthGoogleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 login oauth google internal server error response
func (o *GetAPIV1LoginOauthGoogleInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1LoginOauthGoogleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/login/oauth/google][%d] getApiV1LoginOauthGoogleInternalServerError %s", 500, payload)
}

func (o *GetAPIV1LoginOauthGoogleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/login/oauth/google][%d] getApiV1LoginOauthGoogleInternalServerError %s", 500, payload)
}

func (o *GetAPIV1LoginOauthGoogleInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1LoginOauthGoogleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
