// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1LoginOauthGoogleParams creates a new GetAPIV1LoginOauthGoogleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1LoginOauthGoogleParams() *GetAPIV1LoginOauthGoogleParams {
	return &GetAPIV1LoginOauthGoogleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1LoginOauthGoogleParamsWithTimeout creates a new GetAPIV1LoginOauthGoogleParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1LoginOauthGoogleParamsWithTimeout(timeout time.Duration) *GetAPIV1LoginOauthGoogleParams {
	return &GetAPIV1LoginOauthGoogleParams{
		timeout: timeout,
	}
}

// NewGetAPIV1LoginOauthGoogleParamsWithContext creates a new GetAPIV1LoginOauthGoogleParams object
// with the ability to set a context for a request.
func NewGetAPIV1LoginOauthGoogleParamsWithContext(ctx context.Context) *GetAPIV1LoginOauthGoogleParams {
	return &GetAPIV1LoginOauthGoogleParams{
		Context: ctx,
	}
}

// NewGetAPIV1LoginOauthGoogleParamsWithHTTPClient creates a new GetAPIV1LoginOauthGoogleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1LoginOauthGoogleParamsWithHTTPClient(client *http.Client) *GetAPIV1LoginOauthGoogleParams {
	return &GetAPIV1LoginOauthGoogleParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1LoginOauthGoogleParams contains all the parameters to send to the API endpoint

	for the get API v1 login oauth google operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1LoginOauthGoogleParams struct {

	/* OriginalURI.

	   Original frontend path to redirect after login
	*/
	OriginalURI *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 login oauth google params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1LoginOauthGoogleParams) WithDefaults() *GetAPIV1LoginOauthGoogleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 login oauth google params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1LoginOauthGoogleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) WithTimeout(timeout time.Duration) *GetAPIV1LoginOauthGoogleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) WithContext(ctx context.Context) *GetAPIV1LoginOauthGoogleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) WithHTTPClient(client *http.Client) *GetAPIV1LoginOauthGoogleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOriginalURI adds the originalURI to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) WithOriginalURI(originalURI *string) *GetAPIV1LoginOauthGoogleParams {
	o.SetOriginalURI(originalURI)
	return o
}

// SetOriginalURI adds the originalUri to the get API v1 login oauth google params
func (o *GetAPIV1LoginOauthGoogleParams) SetOriginalURI(originalURI *string) {
	o.OriginalURI = originalURI
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1LoginOauthGoogleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.OriginalURI != nil {

		// query param original_uri
		var qrOriginalURI string

		if o.OriginalURI != nil {
			qrOriginalURI = *o.OriginalURI
		}
		qOriginalURI := qrOriginalURI
		if qOriginalURI != "" {

			if err := r.SetQueryParam("original_uri", qOriginalURI); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
