// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// NewPostAPIV1LoginOauthExchangeGoogleParams creates a new PostAPIV1LoginOauthExchangeGoogleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1LoginOauthExchangeGoogleParams() *PostAPIV1LoginOauthExchangeGoogleParams {
	return &PostAPIV1LoginOauthExchangeGoogleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1LoginOauthExchangeGoogleParamsWithTimeout creates a new PostAPIV1LoginOauthExchangeGoogleParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1LoginOauthExchangeGoogleParamsWithTimeout(timeout time.Duration) *PostAPIV1LoginOauthExchangeGoogleParams {
	return &PostAPIV1LoginOauthExchangeGoogleParams{
		timeout: timeout,
	}
}

// NewPostAPIV1LoginOauthExchangeGoogleParamsWithContext creates a new PostAPIV1LoginOauthExchangeGoogleParams object
// with the ability to set a context for a request.
func NewPostAPIV1LoginOauthExchangeGoogleParamsWithContext(ctx context.Context) *PostAPIV1LoginOauthExchangeGoogleParams {
	return &PostAPIV1LoginOauthExchangeGoogleParams{
		Context: ctx,
	}
}

// NewPostAPIV1LoginOauthExchangeGoogleParamsWithHTTPClient creates a new PostAPIV1LoginOauthExchangeGoogleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1LoginOauthExchangeGoogleParamsWithHTTPClient(client *http.Client) *PostAPIV1LoginOauthExchangeGoogleParams {
	return &PostAPIV1LoginOauthExchangeGoogleParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1LoginOauthExchangeGoogleParams contains all the parameters to send to the API endpoint

	for the post API v1 login oauth exchange google operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1LoginOauthExchangeGoogleParams struct {

	/* Request.

	   Google ID token
	*/
	Request *models.ApiauthmodelsExchangeIDTokenRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 login oauth exchange google params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WithDefaults() *PostAPIV1LoginOauthExchangeGoogleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 login oauth exchange google params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1LoginOauthExchangeGoogleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WithTimeout(timeout time.Duration) *PostAPIV1LoginOauthExchangeGoogleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WithContext(ctx context.Context) *PostAPIV1LoginOauthExchangeGoogleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WithHTTPClient(client *http.Client) *PostAPIV1LoginOauthExchangeGoogleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WithRequest(request *models.ApiauthmodelsExchangeIDTokenRequest) *PostAPIV1LoginOauthExchangeGoogleParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v1 login oauth exchange google params
func (o *PostAPIV1LoginOauthExchangeGoogleParams) SetRequest(request *models.ApiauthmodelsExchangeIDTokenRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1LoginOauthExchangeGoogleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
