// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAPIV1AuthExchangeGoogleReader is a Reader for the PostAPIV1AuthExchangeGoogle structure.
type PostAPIV1AuthExchangeGoogleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuthExchangeGoogleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuthExchangeGoogleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuthExchangeGoogleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuthExchangeGoogleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostAPIV1AuthExchangeGoogleTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuthExchangeGoogleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/auth/exchange/google] PostAPIV1AuthExchangeGoogle", response, response.Code())
	}
}

// NewPostAPIV1AuthExchangeGoogleOK creates a PostAPIV1AuthExchangeGoogleOK with default headers values
func NewPostAPIV1AuthExchangeGoogleOK() *PostAPIV1AuthExchangeGoogleOK {
	return &PostAPIV1AuthExchangeGoogleOK{}
}

/*
PostAPIV1AuthExchangeGoogleOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1AuthExchangeGoogleOK struct {
	Payload *models.ApiauthmodelsTokenPairResponse
}

// IsSuccess returns true when this post Api v1 auth exchange google o k response has a 2xx status code
func (o *PostAPIV1AuthExchangeGoogleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 auth exchange google o k response has a 3xx status code
func (o *PostAPIV1AuthExchangeGoogleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth exchange google o k response has a 4xx status code
func (o *PostAPIV1AuthExchangeGoogleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth exchange google o k response has a 5xx status code
func (o *PostAPIV1AuthExchangeGoogleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth exchange google o k response a status code equal to that given
func (o *PostAPIV1AuthExchangeGoogleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 auth exchange google o k response
func (o *PostAPIV1AuthExchangeGoogleOK) Code() int {
	return 200
}

func (o *PostAPIV1AuthExchangeGoogleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleOK %s", 200, payload)
}

func (o *PostAPIV1AuthExchangeGoogleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleOK %s", 200, payload)
}

func (o *PostAPIV1AuthExchangeGoogleOK) GetPayload() *models.ApiauthmodelsTokenPairResponse {
	return o.Payload
}

func (o *PostAPIV1AuthExchangeGoogleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiauthmodelsTokenPairResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthExchangeGoogleBadRequest creates a PostAPIV1AuthExchangeGoogleBadRequest with default headers values
func NewPostAPIV1AuthExchangeGoogleBadRequest() *PostAPIV1AuthExchangeGoogleBadRequest {
	return &PostAPIV1AuthExchangeGoogleBadRequest{}
}

/*
PostAPIV1AuthExchangeGoogleBadRequest describes a response with status code 400, with default header values.

INVALID_ID_TOKEN or EMAIL_NOT_VERIFIED
*/
type PostAPIV1AuthExchangeGoogleBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 auth exchange google bad request response has a 2xx status code
func (o *PostAPIV1AuthExchangeGoogleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth exchange google bad request response has a 3xx status code
func (o *PostAPIV1AuthExchangeGoogleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth exchange google bad request response has a 4xx status code
func (o *PostAPIV1AuthExchangeGoogleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth exchange google bad request response has a 5xx status code
func (o *PostAPIV1AuthExchangeGoogleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth exchange google bad request response a status code equal to that given
func (o *PostAPIV1AuthExchangeGoogleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 auth exchange google bad request response
func (o *PostAPIV1AuthExchangeGoogleBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuthExchangeGoogleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthExchangeGoogleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthExchangeGoogleBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1AuthExchangeGoogleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthExchangeGoogleForbidden creates a PostAPIV1AuthExchangeGoogleForbidden with default headers values
func NewPostAPIV1AuthExchangeGoogleForbidden() *PostAPIV1AuthExchangeGoogleForbidden {
	return &PostAPIV1AuthExchangeGoogleForbidden{}
}

/*
PostAPIV1AuthExchangeGoogleForbidden describes a response with status code 403, with default header values.

DOMAIN_NOT_ALLOWED
*/
type PostAPIV1AuthExchangeGoogleForbidden struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 auth exchange google forbidden response has a 2xx status code
func (o *PostAPIV1AuthExchangeGoogleForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth exchange google forbidden response has a 3xx status code
func (o *PostAPIV1AuthExchangeGoogleForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth exchange google forbidden response has a 4xx status code
func (o *PostAPIV1AuthExchangeGoogleForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth exchange google forbidden response has a 5xx status code
func (o *PostAPIV1AuthExchangeGoogleForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth exchange google forbidden response a status code equal to that given
func (o *PostAPIV1AuthExchangeGoogleForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 auth exchange google forbidden response
func (o *PostAPIV1AuthExchangeGoogleForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuthExchangeGoogleForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleForbidden %s", 403, payload)
}

func (o *PostAPIV1AuthExchangeGoogleForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleForbidden %s", 403, payload)
}

func (o *PostAPIV1AuthExchangeGoogleForbidden) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1AuthExchangeGoogleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthExchangeGoogleTooManyRequests creates a PostAPIV1AuthExchangeGoogleTooManyRequests with default headers values
func NewPostAPIV1AuthExchangeGoogleTooManyRequests() *PostAPIV1AuthExchangeGoogleTooManyRequests {
	return &PostAPIV1AuthExchangeGoogleTooManyRequests{}
}

/*
PostAPIV1AuthExchangeGoogleTooManyRequests describes a response with status code 429, with default header values.

Rate limit exceeded
*/
type PostAPIV1AuthExchangeGoogleTooManyRequests struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 auth exchange google too many requests response has a 2xx status code
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth exchange google too many requests response has a 3xx status code
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth exchange google too many requests response has a 4xx status code
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth exchange google too many requests response has a 5xx status code
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth exchange google too many requests response a status code equal to that given
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the post Api v1 auth exchange google too many requests response
func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) Code() int {
	return 429
}

func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleTooManyRequests %s", 429, payload)
}

func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleTooManyRequests %s", 429, payload)
}

func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1AuthExchangeGoogleTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthExchangeGoogleInternalServerError creates a PostAPIV1AuthExchangeGoogleInternalServerError with default headers values
func NewPostAPIV1AuthExchangeGoogleInternalServerError() *PostAPIV1AuthExchangeGoogleInternalServerError {
	return &PostAPIV1AuthExchangeGoogleInternalServerError{}
}

/*
PostAPIV1AuthExchangeGoogleInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPIV1AuthExchangeGoogleInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 auth exchange google internal server error response has a 2xx status code
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth exchange google internal server error response has a 3xx status code
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth exchange google internal server error response has a 4xx status code
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth exchange google internal server error response has a 5xx status code
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 auth exchange google internal server error response a status code equal to that given
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 auth exchange google internal server error response
func (o *PostAPIV1AuthExchangeGoogleInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuthExchangeGoogleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleInternalServerError %s", 500, payload)
}

func (o *PostAPIV1AuthExchangeGoogleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/exchange/google][%d] postApiV1AuthExchangeGoogleInternalServerError %s", 500, payload)
}

func (o *PostAPIV1AuthExchangeGoogleInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1AuthExchangeGoogleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
