// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAPIV1RefreshReader is a Reader for the PostAPIV1Refresh structure.
type PostAPIV1RefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1RefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1RefreshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1RefreshBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1RefreshConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1RefreshInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/refresh] PostAPIV1Refresh", response, response.Code())
	}
}

// NewPostAPIV1RefreshOK creates a PostAPIV1RefreshOK with default headers values
func NewPostAPIV1RefreshOK() *PostAPIV1RefreshOK {
	return &PostAPIV1RefreshOK{}
}

/*
PostAPIV1RefreshOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1RefreshOK struct {

	/* Rotated refresh token cookie (if issued)
	 */
	SetCookie string

	Payload *models.ApiauthmodelsTokenPairResponse
}

// IsSuccess returns true when this post Api v1 refresh o k response has a 2xx status code
func (o *PostAPIV1RefreshOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 refresh o k response has a 3xx status code
func (o *PostAPIV1RefreshOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 refresh o k response has a 4xx status code
func (o *PostAPIV1RefreshOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 refresh o k response has a 5xx status code
func (o *PostAPIV1RefreshOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 refresh o k response a status code equal to that given
func (o *PostAPIV1RefreshOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 refresh o k response
func (o *PostAPIV1RefreshOK) Code() int {
	return 200
}

func (o *PostAPIV1RefreshOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshOK %s", 200, payload)
}

func (o *PostAPIV1RefreshOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshOK %s", 200, payload)
}

func (o *PostAPIV1RefreshOK) GetPayload() *models.ApiauthmodelsTokenPairResponse {
	return o.Payload
}

func (o *PostAPIV1RefreshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Set-Cookie
	hdrSetCookie := response.GetHeader("Set-Cookie")

	if hdrSetCookie != "" {
		o.SetCookie = hdrSetCookie
	}

	o.Payload = new(models.ApiauthmodelsTokenPairResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RefreshBadRequest creates a PostAPIV1RefreshBadRequest with default headers values
func NewPostAPIV1RefreshBadRequest() *PostAPIV1RefreshBadRequest {
	return &PostAPIV1RefreshBadRequest{}
}

/*
PostAPIV1RefreshBadRequest describes a response with status code 400, with default header values.

Invalid refresh token
*/
type PostAPIV1RefreshBadRequest struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 refresh bad request response has a 2xx status code
func (o *PostAPIV1RefreshBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 refresh bad request response has a 3xx status code
func (o *PostAPIV1RefreshBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 refresh bad request response has a 4xx status code
func (o *PostAPIV1RefreshBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 refresh bad request response has a 5xx status code
func (o *PostAPIV1RefreshBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 refresh bad request response a status code equal to that given
func (o *PostAPIV1RefreshBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 refresh bad request response
func (o *PostAPIV1RefreshBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1RefreshBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshBadRequest %s", 400, payload)
}

func (o *PostAPIV1RefreshBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshBadRequest %s", 400, payload)
}

func (o *PostAPIV1RefreshBadRequest) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RefreshBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RefreshConflict creates a PostAPIV1RefreshConflict with default headers values
func NewPostAPIV1RefreshConflict() *PostAPIV1RefreshConflict {
	return &PostAPIV1RefreshConflict{}
}

/*
PostAPIV1RefreshConflict describes a response with status code 409, with default header values.

Refresh lock busy or token reuse
*/
type PostAPIV1RefreshConflict struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 refresh conflict response has a 2xx status code
func (o *PostAPIV1RefreshConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 refresh conflict response has a 3xx status code
func (o *PostAPIV1RefreshConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 refresh conflict response has a 4xx status code
func (o *PostAPIV1RefreshConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 refresh conflict response has a 5xx status code
func (o *PostAPIV1RefreshConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 refresh conflict response a status code equal to that given
func (o *PostAPIV1RefreshConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 refresh conflict response
func (o *PostAPIV1RefreshConflict) Code() int {
	return 409
}

func (o *PostAPIV1RefreshConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshConflict %s", 409, payload)
}

func (o *PostAPIV1RefreshConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshConflict %s", 409, payload)
}

func (o *PostAPIV1RefreshConflict) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RefreshConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RefreshInternalServerError creates a PostAPIV1RefreshInternalServerError with default headers values
func NewPostAPIV1RefreshInternalServerError() *PostAPIV1RefreshInternalServerError {
	return &PostAPIV1RefreshInternalServerError{}
}

/*
PostAPIV1RefreshInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPIV1RefreshInternalServerError struct {
	Payload *models.HttperrorsErrorResponse
}

// IsSuccess returns true when this post Api v1 refresh internal server error response has a 2xx status code
func (o *PostAPIV1RefreshInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 refresh internal server error response has a 3xx status code
func (o *PostAPIV1RefreshInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 refresh internal server error response has a 4xx status code
func (o *PostAPIV1RefreshInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 refresh internal server error response has a 5xx status code
func (o *PostAPIV1RefreshInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 refresh internal server error response a status code equal to that given
func (o *PostAPIV1RefreshInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 refresh internal server error response
func (o *PostAPIV1RefreshInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1RefreshInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshInternalServerError %s", 500, payload)
}

func (o *PostAPIV1RefreshInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/refresh][%d] postApiV1RefreshInternalServerError %s", 500, payload)
}

func (o *PostAPIV1RefreshInternalServerError) GetPayload() *models.HttperrorsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RefreshInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
