// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// PostAuthV1LogoutReader is a Reader for the PostAuthV1Logout structure.
type PostAuthV1LogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthV1LogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostAuthV1LogoutNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthV1LogoutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAuthV1LogoutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthV1LogoutInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/v1/logout] PostAuthV1Logout", response, response.Code())
	}
}

// NewPostAuthV1LogoutNoContent creates a PostAuthV1LogoutNoContent with default headers values
func NewPostAuthV1LogoutNoContent() *PostAuthV1LogoutNoContent {
	return &PostAuthV1LogoutNoContent{}
}

/*
PostAuthV1LogoutNoContent describes a response with status code 204, with default header values.

Logged out
*/
type PostAuthV1LogoutNoContent struct {

	/* Cleared refresh token cookie
	 */
	SetCookie string
}

// IsSuccess returns true when this post auth v1 logout no content response has a 2xx status code
func (o *PostAuthV1LogoutNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth v1 logout no content response has a 3xx status code
func (o *PostAuthV1LogoutNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v1 logout no content response has a 4xx status code
func (o *PostAuthV1LogoutNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth v1 logout no content response has a 5xx status code
func (o *PostAuthV1LogoutNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v1 logout no content response a status code equal to that given
func (o *PostAuthV1LogoutNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post auth v1 logout no content response
func (o *PostAuthV1LogoutNoContent) Code() int {
	return 204
}

func (o *PostAuthV1LogoutNoContent) Error() string {
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutNoContent", 204)
}

func (o *PostAuthV1LogoutNoContent) String() string {
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutNoContent", 204)
}

func (o *PostAuthV1LogoutNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Set-Cookie
	hdrSetCookie := response.GetHeader("Set-Cookie")

	if hdrSetCookie != "" {
		o.SetCookie = hdrSetCookie
	}

	return nil
}

// NewPostAuthV1LogoutBadRequest creates a PostAuthV1LogoutBadRequest with default headers values
func NewPostAuthV1LogoutBadRequest() *PostAuthV1LogoutBadRequest {
	return &PostAuthV1LogoutBadRequest{}
}

/*
PostAuthV1LogoutBadRequest describes a response with status code 400, with default header values.

Invalid token
*/
type PostAuthV1LogoutBadRequest struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this post auth v1 logout bad request response has a 2xx status code
func (o *PostAuthV1LogoutBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v1 logout bad request response has a 3xx status code
func (o *PostAuthV1LogoutBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v1 logout bad request response has a 4xx status code
func (o *PostAuthV1LogoutBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth v1 logout bad request response has a 5xx status code
func (o *PostAuthV1LogoutBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v1 logout bad request response a status code equal to that given
func (o *PostAuthV1LogoutBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth v1 logout bad request response
func (o *PostAuthV1LogoutBadRequest) Code() int {
	return 400
}

func (o *PostAuthV1LogoutBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutBadRequest %s", 400, payload)
}

func (o *PostAuthV1LogoutBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutBadRequest %s", 400, payload)
}

func (o *PostAuthV1LogoutBadRequest) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *PostAuthV1LogoutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthV1LogoutUnauthorized creates a PostAuthV1LogoutUnauthorized with default headers values
func NewPostAuthV1LogoutUnauthorized() *PostAuthV1LogoutUnauthorized {
	return &PostAuthV1LogoutUnauthorized{}
}

/*
PostAuthV1LogoutUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAuthV1LogoutUnauthorized struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this post auth v1 logout unauthorized response has a 2xx status code
func (o *PostAuthV1LogoutUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v1 logout unauthorized response has a 3xx status code
func (o *PostAuthV1LogoutUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v1 logout unauthorized response has a 4xx status code
func (o *PostAuthV1LogoutUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth v1 logout unauthorized response has a 5xx status code
func (o *PostAuthV1LogoutUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v1 logout unauthorized response a status code equal to that given
func (o *PostAuthV1LogoutUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post auth v1 logout unauthorized response
func (o *PostAuthV1LogoutUnauthorized) Code() int {
	return 401
}

func (o *PostAuthV1LogoutUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutUnauthorized %s", 401, payload)
}

func (o *PostAuthV1LogoutUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutUnauthorized %s", 401, payload)
}

func (o *PostAuthV1LogoutUnauthorized) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *PostAuthV1LogoutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthV1LogoutInternalServerError creates a PostAuthV1LogoutInternalServerError with default headers values
func NewPostAuthV1LogoutInternalServerError() *PostAuthV1LogoutInternalServerError {
	return &PostAuthV1LogoutInternalServerError{}
}

/*
PostAuthV1LogoutInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAuthV1LogoutInternalServerError struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this post auth v1 logout internal server error response has a 2xx status code
func (o *PostAuthV1LogoutInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v1 logout internal server error response has a 3xx status code
func (o *PostAuthV1LogoutInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v1 logout internal server error response has a 4xx status code
func (o *PostAuthV1LogoutInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth v1 logout internal server error response has a 5xx status code
func (o *PostAuthV1LogoutInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth v1 logout internal server error response a status code equal to that given
func (o *PostAuthV1LogoutInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post auth v1 logout internal server error response
func (o *PostAuthV1LogoutInternalServerError) Code() int {
	return 500
}

func (o *PostAuthV1LogoutInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutInternalServerError %s", 500, payload)
}

func (o *PostAuthV1LogoutInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1/logout][%d] postAuthV1LogoutInternalServerError %s", 500, payload)
}

func (o *PostAuthV1LogoutInternalServerError) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *PostAuthV1LogoutInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
