// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// NewPostAuthS2sV1IntrospectParams creates a new PostAuthS2sV1IntrospectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthS2sV1IntrospectParams() *PostAuthS2sV1IntrospectParams {
	return &PostAuthS2sV1IntrospectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthS2sV1IntrospectParamsWithTimeout creates a new PostAuthS2sV1IntrospectParams object
// with the ability to set a timeout on a request.
func NewPostAuthS2sV1IntrospectParamsWithTimeout(timeout time.Duration) *PostAuthS2sV1IntrospectParams {
	return &PostAuthS2sV1IntrospectParams{
		timeout: timeout,
	}
}

// NewPostAuthS2sV1IntrospectParamsWithContext creates a new PostAuthS2sV1IntrospectParams object
// with the ability to set a context for a request.
func NewPostAuthS2sV1IntrospectParamsWithContext(ctx context.Context) *PostAuthS2sV1IntrospectParams {
	return &PostAuthS2sV1IntrospectParams{
		Context: ctx,
	}
}

// NewPostAuthS2sV1IntrospectParamsWithHTTPClient creates a new PostAuthS2sV1IntrospectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthS2sV1IntrospectParamsWithHTTPClient(client *http.Client) *PostAuthS2sV1IntrospectParams {
	return &PostAuthS2sV1IntrospectParams{
		HTTPClient: client,
	}
}

/*
PostAuthS2sV1IntrospectParams contains all the parameters to send to the API endpoint

	for the post auth s2s v1 introspect operation.

	Typically these are written to a http.Request.
*/
type PostAuthS2sV1IntrospectParams struct {

	/* Request.

	   Introspect request
	*/
	Request *models.ApiauthmodelsIntrospectRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth s2s v1 introspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthS2sV1IntrospectParams) WithDefaults() *PostAuthS2sV1IntrospectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth s2s v1 introspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthS2sV1IntrospectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) WithTimeout(timeout time.Duration) *PostAuthS2sV1IntrospectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) WithContext(ctx context.Context) *PostAuthS2sV1IntrospectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) WithHTTPClient(client *http.Client) *PostAuthS2sV1IntrospectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) WithRequest(request *models.ApiauthmodelsIntrospectRequest) *PostAuthS2sV1IntrospectParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post auth s2s v1 introspect params
func (o *PostAuthS2sV1IntrospectParams) SetRequest(request *models.ApiauthmodelsIntrospectRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthS2sV1IntrospectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
