// Package authclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package authclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ApimodelsRole.
const (
	RoleAdmin    ApimodelsRole = "admin"
	RoleEditor   ApimodelsRole = "editor"
	RoleGuest    ApimodelsRole = "guest"
	RoleReviewer ApimodelsRole = "reviewer"
)

// Valid indicates whether the value is a known member of the ApimodelsRole enum.
func (e ApimodelsRole) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleEditor:
		return true
	case RoleGuest:
		return true
	case RoleReviewer:
		return true
	default:
		return false
	}
}

// Defines values for EntityAuditAction.
const (
	AuditActionLoginFailed   EntityAuditAction = "login_failed"
	AuditActionLoginSuccess  EntityAuditAction = "login_success"
	AuditActionLogoutSuccess EntityAuditAction = "logout_success"
	AuditActionRoleAssigned  EntityAuditAction = "assigned"
	AuditActionRoleRevoked   EntityAuditAction = "revoked"
	AuditActionRolesReplaced EntityAuditAction = "replaced"
)

// Valid indicates whether the value is a known member of the EntityAuditAction enum.
func (e EntityAuditAction) Valid() bool {
	switch e {
	case AuditActionLoginFailed:
		return true
	case AuditActionLoginSuccess:
		return true
	case AuditActionLogoutSuccess:
		return true
	case AuditActionRoleAssigned:
		return true
	case AuditActionRoleRevoked:
		return true
	case AuditActionRolesReplaced:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1LoginOauthGoogleParamsOauthCallbackType.
const (
	Html GetApiV1LoginOauthGoogleParamsOauthCallbackType = "html"
	Json GetApiV1LoginOauthGoogleParamsOauthCallbackType = "json"
)

// Valid indicates whether the value is a known member of the GetApiV1LoginOauthGoogleParamsOauthCallbackType enum.
func (e GetApiV1LoginOauthGoogleParamsOauthCallbackType) Valid() bool {
	switch e {
	case Html:
		return true
	case Json:
		return true
	default:
		return false
	}
}

// ApiauthmodelsAuditLog defines model for apiauthmodels.AuditLog.
type ApiauthmodelsAuditLog struct {
	Action     *EntityAuditAction `json:"action,omitempty"`
	Actor      *string            `json:"actor,omitempty"`
	CreatedAt  *string            `json:"created_at,omitempty"`
	Details    *string            `json:"details,omitempty"`
	EntityId   *string            `json:"entity_id,omitempty"`
	EntityType *string            `json:"entity_type,omitempty"`
	Id         *string            `json:"id,omitempty"`
	TargetId   *string            `json:"target_id,omitempty"`
	TargetType *string            `json:"target_type,omitempty"`
}

// ApiauthmodelsAuditLogResponse defines model for apiauthmodels.AuditLogResponse.
type ApiauthmodelsAuditLogResponse struct {
	Logs *[]ApiauthmodelsAuditLog `json:"logs,omitempty"`
}

// ApiauthmodelsExchangeIDTokenRequest defines model for apiauthmodels.ExchangeIDTokenRequest.
type ApiauthmodelsExchangeIDTokenRequest struct {
	// IdToken IDToken is the upstream provider's signed JWT.
	IdToken *string `json:"id_token,omitempty"`
}

// ApiauthmodelsIntrospectRequest defines model for apiauthmodels.IntrospectRequest.
type ApiauthmodelsIntrospectRequest struct {
	AccessToken *string `json:"access_token,omitempty"`
}

// ApiauthmodelsIntrospectResponse defines model for apiauthmodels.IntrospectResponse.
type ApiauthmodelsIntrospectResponse struct {
	Active *bool     `json:"active,omitempty"`
	Email  *string   `json:"email,omitempty"`
	Exp    *int      `json:"exp,omitempty"`
	Jti    *string   `json:"jti,omitempty"`
	Roles  *[]string `json:"roles,omitempty"`
	Sub    *string   `json:"sub,omitempty"`
}

// ApiauthmodelsJWKSResponse defines model for apiauthmodels.JWKSResponse.
type ApiauthmodelsJWKSResponse struct {
	Keys *[]EntityJWK `json:"keys,omitempty"`
}

// ApiauthmodelsMeResponse defines model for apiauthmodels.MeResponse.
type ApiauthmodelsMeResponse struct {
	DisplayName   *string   `json:"display_name,omitempty"`
	Email         *string   `json:"email,omitempty"`
	Id            *string   `json:"id,omitempty"`
	OauthProvider *string   `json:"oauth_provider,omitempty"`
	Roles         *[]string `json:"roles,omitempty"`
}

// ApiauthmodelsOAuthCallbackJSONResponse defines model for apiauthmodels.OAuthCallbackJSONResponse.
type ApiauthmodelsOAuthCallbackJSONResponse struct {
	OriginalUri *string                         `json:"original_uri,omitempty"`
	Token       *ApiauthmodelsTokenPairResponse `json:"token,omitempty"`
}

// ApiauthmodelsTokenPairResponse defines model for apiauthmodels.TokenPairResponse.
type ApiauthmodelsTokenPairResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int    `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// ApimodelsAssignRoleRequest defines model for apimodels.AssignRoleRequest.
type ApimodelsAssignRoleRequest struct {
	Role   *ApimodelsRole `json:"role,omitempty"`
	UserId *string        `json:"user_id,omitempty"`
}

// ApimodelsListRolesResponse defines model for apimodels.ListRolesResponse.
type ApimodelsListRolesResponse struct {
	Roles *[]ApimodelsRole `json:"roles,omitempty"`
}

// ApimodelsRevokeRoleRequest defines model for apimodels.RevokeRoleRequest.
type ApimodelsRevokeRoleRequest struct {
	Role   *ApimodelsRole `json:"role,omitempty"`
	UserId *string        `json:"user_id,omitempty"`
}

// ApimodelsRole defines model for apimodels.Role.
type ApimodelsRole string

// AuthRefreshTokenJSONRequest defines model for auth.refreshTokenJSONRequest.
type AuthRefreshTokenJSONRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// EntityAuditAction defines model for entity.AuditAction.
type EntityAuditAction string

// EntityJWK defines model for entity.JWK.
type EntityJWK struct {
	Alg *string `json:"alg,omitempty"`
	Crv *string `json:"crv,omitempty"`
	Kid *string `json:"kid,omitempty"`
	Kty *string `json:"kty,omitempty"`
	Use *string `json:"use,omitempty"`
	X   *string `json:"x,omitempty"`
	Y   *string `json:"y,omitempty"`
}

// HttperrorsErrorResponse defines model for httperrors.ErrorResponse.
type HttperrorsErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetApiV1AuditLogParams defines parameters for GetApiV1AuditLog.
type GetApiV1AuditLogParams struct {
	// Limit Number of entries to return (max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Action Filter by audit action (e.g. assigned, revoked, login_success)
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Actor Filter by actor (exact match)
	Actor *string `form:"actor,omitempty" json:"actor,omitempty"`

	// CreatedFrom Filter by created_at >= this RFC3339 timestamp
	CreatedFrom *string `form:"created_from,omitempty" json:"created_from,omitempty"`

	// CreatedTo Filter by created_at <= this RFC3339 timestamp
	CreatedTo *string `form:"created_to,omitempty" json:"created_to,omitempty"`
}

// GetApiV1LoginOauthGoogleParams defines parameters for GetApiV1LoginOauthGoogle.
type GetApiV1LoginOauthGoogleParams struct {
	// OriginalUri Original frontend path to redirect after login
	OriginalUri *string `form:"original_uri,omitempty" json:"original_uri,omitempty"`

	// OauthCallbackType Callback response shape: `json` (default, server-side BFF) or `html` (legacy handoff for local testing)
	OauthCallbackType *GetApiV1LoginOauthGoogleParamsOauthCallbackType `form:"oauth_callback_type,omitempty" json:"oauth_callback_type,omitempty"`
}

// GetApiV1LoginOauthGoogleParamsOauthCallbackType defines parameters for GetApiV1LoginOauthGoogle.
type GetApiV1LoginOauthGoogleParamsOauthCallbackType string

// GetApiV1LoginOauthGoogleCallbackParams defines parameters for GetApiV1LoginOauthGoogleCallback.
type GetApiV1LoginOauthGoogleCallbackParams struct {
	// Code OAuth authorization code returned by the provider
	Code string `form:"code" json:"code"`

	// State Signed opaque state (HMAC + expiry) issued by /login/oauth/google; carries the HTML/JSON mode flag set at login time
	State string `form:"state" json:"state"`

	// Accept Optional override: `application/json` forces JSON mode regardless of the state flag (JSON is already the default).
	Accept *string `json:"Accept,omitempty"`
}

// PostApiV1LogoutParams defines parameters for PostApiV1Logout.
type PostApiV1LogoutParams struct {
	// Authorization Bearer access token
	Authorization *string `json:"Authorization,omitempty"`
}

// PostApiV1LogoutAllParams defines parameters for PostApiV1LogoutAll.
type PostApiV1LogoutAllParams struct {
	// Authorization Bearer access token
	Authorization string `json:"Authorization"`
}

// PostApiV1LoginOauthExchangeGoogleJSONRequestBody defines body for PostApiV1LoginOauthExchangeGoogle for application/json ContentType.
type PostApiV1LoginOauthExchangeGoogleJSONRequestBody = ApiauthmodelsExchangeIDTokenRequest

// PostApiV1LogoutJSONRequestBody defines body for PostApiV1Logout for application/json ContentType.
type PostApiV1LogoutJSONRequestBody = AuthRefreshTokenJSONRequest

// PostApiV1RefreshJSONRequestBody defines body for PostApiV1Refresh for application/json ContentType.
type PostApiV1RefreshJSONRequestBody = AuthRefreshTokenJSONRequest

// PostApiV1RolesAssignJSONRequestBody defines body for PostApiV1RolesAssign for application/json ContentType.
type PostApiV1RolesAssignJSONRequestBody = ApimodelsAssignRoleRequest

// PostApiV1RolesRevokeJSONRequestBody defines body for PostApiV1RolesRevoke for application/json ContentType.
type PostApiV1RolesRevokeJSONRequestBody = ApimodelsRevokeRoleRequest

// PostApiV1S2sIntrospectJSONRequestBody defines body for PostApiV1S2sIntrospect for application/json ContentType.
type PostApiV1S2sIntrospectJSONRequestBody = ApiauthmodelsIntrospectRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiV1WellKnownJwksJson request
	GetApiV1WellKnownJwksJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1AuditLog request
	GetApiV1AuditLog(ctx context.Context, params *GetApiV1AuditLogParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1LoginOauthExchangeGoogleWithBody request with any body
	PostApiV1LoginOauthExchangeGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1LoginOauthExchangeGoogle(ctx context.Context, body PostApiV1LoginOauthExchangeGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1LoginOauthGoogle request
	GetApiV1LoginOauthGoogle(ctx context.Context, params *GetApiV1LoginOauthGoogleParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1LoginOauthGoogleCallback request
	GetApiV1LoginOauthGoogleCallback(ctx context.Context, params *GetApiV1LoginOauthGoogleCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1LogoutWithBody request with any body
	PostApiV1LogoutWithBody(ctx context.Context, params *PostApiV1LogoutParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Logout(ctx context.Context, params *PostApiV1LogoutParams, body PostApiV1LogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1LogoutAll request
	PostApiV1LogoutAll(ctx context.Context, params *PostApiV1LogoutAllParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Me request
	GetApiV1Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1RefreshWithBody request with any body
	PostApiV1RefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Refresh(ctx context.Context, body PostApiV1RefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Roles request
	GetApiV1Roles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1RolesAssignWithBody request with any body
	PostApiV1RolesAssignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1RolesAssign(ctx context.Context, body PostApiV1RolesAssignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1RolesRevokeWithBody request with any body
	PostApiV1RolesRevokeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1RolesRevoke(ctx context.Context, body PostApiV1RolesRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1S2sIntrospectWithBody request with any body
	PostApiV1S2sIntrospectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1S2sIntrospect(ctx context.Context, body PostApiV1S2sIntrospectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1UserIdRoles request
	GetApiV1UserIdRoles(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiV1WellKnownJwksJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1WellKnownJwksJsonRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1AuditLog(ctx context.Context, params *GetApiV1AuditLogParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1AuditLogRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1LoginOauthExchangeGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1LoginOauthExchangeGoogleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1LoginOauthExchangeGoogle(ctx context.Context, body PostApiV1LoginOauthExchangeGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1LoginOauthExchangeGoogleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1LoginOauthGoogle(ctx context.Context, params *GetApiV1LoginOauthGoogleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1LoginOauthGoogleRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1LoginOauthGoogleCallback(ctx context.Context, params *GetApiV1LoginOauthGoogleCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1LoginOauthGoogleCallbackRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1LogoutWithBody(ctx context.Context, params *PostApiV1LogoutParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1LogoutRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Logout(ctx context.Context, params *PostApiV1LogoutParams, body PostApiV1LogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1LogoutRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1LogoutAll(ctx context.Context, params *PostApiV1LogoutAllParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1LogoutAllRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1MeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RefreshRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Refresh(ctx context.Context, body PostApiV1RefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RefreshRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Roles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1RolesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RolesAssignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RolesAssignRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RolesAssign(ctx context.Context, body PostApiV1RolesAssignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RolesAssignRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RolesRevokeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RolesRevokeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RolesRevoke(ctx context.Context, body PostApiV1RolesRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RolesRevokeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1S2sIntrospectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1S2sIntrospectRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1S2sIntrospect(ctx context.Context, body PostApiV1S2sIntrospectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1S2sIntrospectRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1UserIdRoles(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1UserIdRolesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiV1WellKnownJwksJsonRequest generates requests for GetApiV1WellKnownJwksJson
func NewGetApiV1WellKnownJwksJsonRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/.well-known/jwks.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1AuditLogRequest generates requests for GetApiV1AuditLog
func NewGetApiV1AuditLogRequest(server string, params *GetApiV1AuditLogParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/audit/log")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "action", *params.Action, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Actor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "actor", *params.Actor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedFrom != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_from", *params.CreatedFrom, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedTo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_to", *params.CreatedTo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1LoginOauthExchangeGoogleRequest calls the generic PostApiV1LoginOauthExchangeGoogle builder with application/json body
func NewPostApiV1LoginOauthExchangeGoogleRequest(server string, body PostApiV1LoginOauthExchangeGoogleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1LoginOauthExchangeGoogleRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1LoginOauthExchangeGoogleRequestWithBody generates requests for PostApiV1LoginOauthExchangeGoogle with any type of body
func NewPostApiV1LoginOauthExchangeGoogleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/login/oauth/exchange/google")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1LoginOauthGoogleRequest generates requests for GetApiV1LoginOauthGoogle
func NewGetApiV1LoginOauthGoogleRequest(server string, params *GetApiV1LoginOauthGoogleParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/login/oauth/google")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.OriginalUri != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "original_uri", *params.OriginalUri, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.OauthCallbackType != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "oauth_callback_type", *params.OauthCallbackType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1LoginOauthGoogleCallbackRequest generates requests for GetApiV1LoginOauthGoogleCallback
func NewGetApiV1LoginOauthGoogleCallbackRequest(server string, params *GetApiV1LoginOauthGoogleCallbackParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/login/oauth/google/callback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "code", params.Code, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

	}

	return req, nil
}

// NewPostApiV1LogoutRequest calls the generic PostApiV1Logout builder with application/json body
func NewPostApiV1LogoutRequest(server string, params *PostApiV1LogoutParams, body PostApiV1LogoutJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1LogoutRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostApiV1LogoutRequestWithBody generates requests for PostApiV1Logout with any type of body
func NewPostApiV1LogoutRequestWithBody(server string, params *PostApiV1LogoutParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/logout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Authorization != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", *params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Authorization", headerParam0)
		}

	}

	return req, nil
}

// NewPostApiV1LogoutAllRequest generates requests for PostApiV1LogoutAll
func NewPostApiV1LogoutAllRequest(server string, params *PostApiV1LogoutAllParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/logout/all")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetApiV1MeRequest generates requests for GetApiV1Me
func NewGetApiV1MeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1RefreshRequest calls the generic PostApiV1Refresh builder with application/json body
func NewPostApiV1RefreshRequest(server string, body PostApiV1RefreshJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1RefreshRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1RefreshRequestWithBody generates requests for PostApiV1Refresh with any type of body
func NewPostApiV1RefreshRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1RolesRequest generates requests for GetApiV1Roles
func NewGetApiV1RolesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/roles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1RolesAssignRequest calls the generic PostApiV1RolesAssign builder with application/json body
func NewPostApiV1RolesAssignRequest(server string, body PostApiV1RolesAssignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1RolesAssignRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1RolesAssignRequestWithBody generates requests for PostApiV1RolesAssign with any type of body
func NewPostApiV1RolesAssignRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/roles/assign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1RolesRevokeRequest calls the generic PostApiV1RolesRevoke builder with application/json body
func NewPostApiV1RolesRevokeRequest(server string, body PostApiV1RolesRevokeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1RolesRevokeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1RolesRevokeRequestWithBody generates requests for PostApiV1RolesRevoke with any type of body
func NewPostApiV1RolesRevokeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/roles/revoke")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1S2sIntrospectRequest calls the generic PostApiV1S2sIntrospect builder with application/json body
func NewPostApiV1S2sIntrospectRequest(server string, body PostApiV1S2sIntrospectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1S2sIntrospectRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1S2sIntrospectRequestWithBody generates requests for PostApiV1S2sIntrospect with any type of body
func NewPostApiV1S2sIntrospectRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/s2s/introspect")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1UserIdRolesRequest generates requests for GetApiV1UserIdRoles
func NewGetApiV1UserIdRolesRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/user/%s/roles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiV1WellKnownJwksJsonWithResponse request
	GetApiV1WellKnownJwksJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1WellKnownJwksJsonResponse, error)

	// GetApiV1AuditLogWithResponse request
	GetApiV1AuditLogWithResponse(ctx context.Context, params *GetApiV1AuditLogParams, reqEditors ...RequestEditorFn) (*GetApiV1AuditLogResponse, error)

	// PostApiV1LoginOauthExchangeGoogleWithBodyWithResponse request with any body
	PostApiV1LoginOauthExchangeGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1LoginOauthExchangeGoogleResponse, error)

	PostApiV1LoginOauthExchangeGoogleWithResponse(ctx context.Context, body PostApiV1LoginOauthExchangeGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1LoginOauthExchangeGoogleResponse, error)

	// GetApiV1LoginOauthGoogleWithResponse request
	GetApiV1LoginOauthGoogleWithResponse(ctx context.Context, params *GetApiV1LoginOauthGoogleParams, reqEditors ...RequestEditorFn) (*GetApiV1LoginOauthGoogleResponse, error)

	// GetApiV1LoginOauthGoogleCallbackWithResponse request
	GetApiV1LoginOauthGoogleCallbackWithResponse(ctx context.Context, params *GetApiV1LoginOauthGoogleCallbackParams, reqEditors ...RequestEditorFn) (*GetApiV1LoginOauthGoogleCallbackResponse, error)

	// PostApiV1LogoutWithBodyWithResponse request with any body
	PostApiV1LogoutWithBodyWithResponse(ctx context.Context, params *PostApiV1LogoutParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1LogoutResponse, error)

	PostApiV1LogoutWithResponse(ctx context.Context, params *PostApiV1LogoutParams, body PostApiV1LogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1LogoutResponse, error)

	// PostApiV1LogoutAllWithResponse request
	PostApiV1LogoutAllWithResponse(ctx context.Context, params *PostApiV1LogoutAllParams, reqEditors ...RequestEditorFn) (*PostApiV1LogoutAllResponse, error)

	// GetApiV1MeWithResponse request
	GetApiV1MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1MeResponse, error)

	// PostApiV1RefreshWithBodyWithResponse request with any body
	PostApiV1RefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RefreshResponse, error)

	PostApiV1RefreshWithResponse(ctx context.Context, body PostApiV1RefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RefreshResponse, error)

	// GetApiV1RolesWithResponse request
	GetApiV1RolesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1RolesResponse, error)

	// PostApiV1RolesAssignWithBodyWithResponse request with any body
	PostApiV1RolesAssignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RolesAssignResponse, error)

	PostApiV1RolesAssignWithResponse(ctx context.Context, body PostApiV1RolesAssignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RolesAssignResponse, error)

	// PostApiV1RolesRevokeWithBodyWithResponse request with any body
	PostApiV1RolesRevokeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RolesRevokeResponse, error)

	PostApiV1RolesRevokeWithResponse(ctx context.Context, body PostApiV1RolesRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RolesRevokeResponse, error)

	// PostApiV1S2sIntrospectWithBodyWithResponse request with any body
	PostApiV1S2sIntrospectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1S2sIntrospectResponse, error)

	PostApiV1S2sIntrospectWithResponse(ctx context.Context, body PostApiV1S2sIntrospectJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1S2sIntrospectResponse, error)

	// GetApiV1UserIdRolesWithResponse request
	GetApiV1UserIdRolesWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetApiV1UserIdRolesResponse, error)
}

type GetApiV1WellKnownJwksJsonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsJWKSResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1WellKnownJwksJsonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1WellKnownJwksJsonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1WellKnownJwksJsonResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1AuditLogResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsAuditLogResponse
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1AuditLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1AuditLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1AuditLogResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1LoginOauthExchangeGoogleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsTokenPairResponse
	JSON400      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
	JSON429      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1LoginOauthExchangeGoogleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1LoginOauthExchangeGoogleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1LoginOauthExchangeGoogleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1LoginOauthGoogleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetApiV1LoginOauthGoogleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1LoginOauthGoogleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1LoginOauthGoogleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1LoginOauthGoogleCallbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetApiV1LoginOauthGoogleCallbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1LoginOauthGoogleCallbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1LoginOauthGoogleCallbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1LogoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1LogoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1LogoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1LogoutResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1LogoutAllResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1LogoutAllResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1LogoutAllResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1LogoutAllResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1MeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsMeResponse
	JSON401      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1MeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1MeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1MeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1RefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsTokenPairResponse
	JSON400      *HttperrorsErrorResponse
	JSON409      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1RefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1RefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1RefreshResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1RolesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApimodelsListRolesResponse
	JSON401      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1RolesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1RolesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1RolesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1RolesAssignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1RolesAssignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1RolesAssignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1RolesAssignResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1RolesRevokeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1RolesRevokeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1RolesRevokeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1RolesRevokeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiV1S2sIntrospectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiauthmodelsIntrospectResponse
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1S2sIntrospectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1S2sIntrospectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiV1S2sIntrospectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiV1UserIdRolesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApimodelsListRolesResponse
	JSON400      *HttperrorsErrorResponse
	JSON401      *HttperrorsErrorResponse
	JSON403      *HttperrorsErrorResponse
	JSON500      *HttperrorsErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1UserIdRolesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1UserIdRolesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiV1UserIdRolesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiV1WellKnownJwksJsonWithResponse request returning *GetApiV1WellKnownJwksJsonResponse
func (c *ClientWithResponses) GetApiV1WellKnownJwksJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1WellKnownJwksJsonResponse, error) {
	rsp, err := c.GetApiV1WellKnownJwksJson(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1WellKnownJwksJsonResponse(rsp)
}

// GetApiV1AuditLogWithResponse request returning *GetApiV1AuditLogResponse
func (c *ClientWithResponses) GetApiV1AuditLogWithResponse(ctx context.Context, params *GetApiV1AuditLogParams, reqEditors ...RequestEditorFn) (*GetApiV1AuditLogResponse, error) {
	rsp, err := c.GetApiV1AuditLog(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1AuditLogResponse(rsp)
}

// PostApiV1LoginOauthExchangeGoogleWithBodyWithResponse request with arbitrary body returning *PostApiV1LoginOauthExchangeGoogleResponse
func (c *ClientWithResponses) PostApiV1LoginOauthExchangeGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1LoginOauthExchangeGoogleResponse, error) {
	rsp, err := c.PostApiV1LoginOauthExchangeGoogleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1LoginOauthExchangeGoogleResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1LoginOauthExchangeGoogleWithResponse(ctx context.Context, body PostApiV1LoginOauthExchangeGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1LoginOauthExchangeGoogleResponse, error) {
	rsp, err := c.PostApiV1LoginOauthExchangeGoogle(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1LoginOauthExchangeGoogleResponse(rsp)
}

// GetApiV1LoginOauthGoogleWithResponse request returning *GetApiV1LoginOauthGoogleResponse
func (c *ClientWithResponses) GetApiV1LoginOauthGoogleWithResponse(ctx context.Context, params *GetApiV1LoginOauthGoogleParams, reqEditors ...RequestEditorFn) (*GetApiV1LoginOauthGoogleResponse, error) {
	rsp, err := c.GetApiV1LoginOauthGoogle(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1LoginOauthGoogleResponse(rsp)
}

// GetApiV1LoginOauthGoogleCallbackWithResponse request returning *GetApiV1LoginOauthGoogleCallbackResponse
func (c *ClientWithResponses) GetApiV1LoginOauthGoogleCallbackWithResponse(ctx context.Context, params *GetApiV1LoginOauthGoogleCallbackParams, reqEditors ...RequestEditorFn) (*GetApiV1LoginOauthGoogleCallbackResponse, error) {
	rsp, err := c.GetApiV1LoginOauthGoogleCallback(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1LoginOauthGoogleCallbackResponse(rsp)
}

// PostApiV1LogoutWithBodyWithResponse request with arbitrary body returning *PostApiV1LogoutResponse
func (c *ClientWithResponses) PostApiV1LogoutWithBodyWithResponse(ctx context.Context, params *PostApiV1LogoutParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1LogoutResponse, error) {
	rsp, err := c.PostApiV1LogoutWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1LogoutResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1LogoutWithResponse(ctx context.Context, params *PostApiV1LogoutParams, body PostApiV1LogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1LogoutResponse, error) {
	rsp, err := c.PostApiV1Logout(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1LogoutResponse(rsp)
}

// PostApiV1LogoutAllWithResponse request returning *PostApiV1LogoutAllResponse
func (c *ClientWithResponses) PostApiV1LogoutAllWithResponse(ctx context.Context, params *PostApiV1LogoutAllParams, reqEditors ...RequestEditorFn) (*PostApiV1LogoutAllResponse, error) {
	rsp, err := c.PostApiV1LogoutAll(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1LogoutAllResponse(rsp)
}

// GetApiV1MeWithResponse request returning *GetApiV1MeResponse
func (c *ClientWithResponses) GetApiV1MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1MeResponse, error) {
	rsp, err := c.GetApiV1Me(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1MeResponse(rsp)
}

// PostApiV1RefreshWithBodyWithResponse request with arbitrary body returning *PostApiV1RefreshResponse
func (c *ClientWithResponses) PostApiV1RefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RefreshResponse, error) {
	rsp, err := c.PostApiV1RefreshWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RefreshResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1RefreshWithResponse(ctx context.Context, body PostApiV1RefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RefreshResponse, error) {
	rsp, err := c.PostApiV1Refresh(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RefreshResponse(rsp)
}

// GetApiV1RolesWithResponse request returning *GetApiV1RolesResponse
func (c *ClientWithResponses) GetApiV1RolesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1RolesResponse, error) {
	rsp, err := c.GetApiV1Roles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1RolesResponse(rsp)
}

// PostApiV1RolesAssignWithBodyWithResponse request with arbitrary body returning *PostApiV1RolesAssignResponse
func (c *ClientWithResponses) PostApiV1RolesAssignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RolesAssignResponse, error) {
	rsp, err := c.PostApiV1RolesAssignWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RolesAssignResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1RolesAssignWithResponse(ctx context.Context, body PostApiV1RolesAssignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RolesAssignResponse, error) {
	rsp, err := c.PostApiV1RolesAssign(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RolesAssignResponse(rsp)
}

// PostApiV1RolesRevokeWithBodyWithResponse request with arbitrary body returning *PostApiV1RolesRevokeResponse
func (c *ClientWithResponses) PostApiV1RolesRevokeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RolesRevokeResponse, error) {
	rsp, err := c.PostApiV1RolesRevokeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RolesRevokeResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1RolesRevokeWithResponse(ctx context.Context, body PostApiV1RolesRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RolesRevokeResponse, error) {
	rsp, err := c.PostApiV1RolesRevoke(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RolesRevokeResponse(rsp)
}

// PostApiV1S2sIntrospectWithBodyWithResponse request with arbitrary body returning *PostApiV1S2sIntrospectResponse
func (c *ClientWithResponses) PostApiV1S2sIntrospectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1S2sIntrospectResponse, error) {
	rsp, err := c.PostApiV1S2sIntrospectWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1S2sIntrospectResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1S2sIntrospectWithResponse(ctx context.Context, body PostApiV1S2sIntrospectJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1S2sIntrospectResponse, error) {
	rsp, err := c.PostApiV1S2sIntrospect(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1S2sIntrospectResponse(rsp)
}

// GetApiV1UserIdRolesWithResponse request returning *GetApiV1UserIdRolesResponse
func (c *ClientWithResponses) GetApiV1UserIdRolesWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetApiV1UserIdRolesResponse, error) {
	rsp, err := c.GetApiV1UserIdRoles(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1UserIdRolesResponse(rsp)
}

// ParseGetApiV1WellKnownJwksJsonResponse parses an HTTP response from a GetApiV1WellKnownJwksJsonWithResponse call
func ParseGetApiV1WellKnownJwksJsonResponse(rsp *http.Response) (*GetApiV1WellKnownJwksJsonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1WellKnownJwksJsonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsJWKSResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1AuditLogResponse parses an HTTP response from a GetApiV1AuditLogWithResponse call
func ParseGetApiV1AuditLogResponse(rsp *http.Response) (*GetApiV1AuditLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1AuditLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsAuditLogResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1LoginOauthExchangeGoogleResponse parses an HTTP response from a PostApiV1LoginOauthExchangeGoogleWithResponse call
func ParsePostApiV1LoginOauthExchangeGoogleResponse(rsp *http.Response) (*PostApiV1LoginOauthExchangeGoogleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1LoginOauthExchangeGoogleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsTokenPairResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1LoginOauthGoogleResponse parses an HTTP response from a GetApiV1LoginOauthGoogleWithResponse call
func ParseGetApiV1LoginOauthGoogleResponse(rsp *http.Response) (*GetApiV1LoginOauthGoogleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1LoginOauthGoogleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV1LoginOauthGoogleCallbackResponse parses an HTTP response from a GetApiV1LoginOauthGoogleCallbackWithResponse call
func ParseGetApiV1LoginOauthGoogleCallbackResponse(rsp *http.Response) (*GetApiV1LoginOauthGoogleCallbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1LoginOauthGoogleCallbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostApiV1LogoutResponse parses an HTTP response from a PostApiV1LogoutWithResponse call
func ParsePostApiV1LogoutResponse(rsp *http.Response) (*PostApiV1LogoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1LogoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1LogoutAllResponse parses an HTTP response from a PostApiV1LogoutAllWithResponse call
func ParsePostApiV1LogoutAllResponse(rsp *http.Response) (*PostApiV1LogoutAllResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1LogoutAllResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1MeResponse parses an HTTP response from a GetApiV1MeWithResponse call
func ParseGetApiV1MeResponse(rsp *http.Response) (*GetApiV1MeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1MeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsMeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1RefreshResponse parses an HTTP response from a PostApiV1RefreshWithResponse call
func ParsePostApiV1RefreshResponse(rsp *http.Response) (*PostApiV1RefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1RefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsTokenPairResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1RolesResponse parses an HTTP response from a GetApiV1RolesWithResponse call
func ParseGetApiV1RolesResponse(rsp *http.Response) (*GetApiV1RolesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1RolesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApimodelsListRolesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostApiV1RolesAssignResponse parses an HTTP response from a PostApiV1RolesAssignWithResponse call
func ParsePostApiV1RolesAssignResponse(rsp *http.Response) (*PostApiV1RolesAssignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1RolesAssignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1RolesRevokeResponse parses an HTTP response from a PostApiV1RolesRevokeWithResponse call
func ParsePostApiV1RolesRevokeResponse(rsp *http.Response) (*PostApiV1RolesRevokeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1RolesRevokeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1S2sIntrospectResponse parses an HTTP response from a PostApiV1S2sIntrospectWithResponse call
func ParsePostApiV1S2sIntrospectResponse(rsp *http.Response) (*PostApiV1S2sIntrospectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1S2sIntrospectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiauthmodelsIntrospectResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1UserIdRolesResponse parses an HTTP response from a GetApiV1UserIdRolesWithResponse call
func ParseGetApiV1UserIdRolesResponse(rsp *http.Response) (*GetApiV1UserIdRolesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1UserIdRolesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApimodelsListRolesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HttperrorsErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
