{
 "title": "MaintMode Logs",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Logs Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name)(count_over_time({service_name=~\"$service\"} | logfmt [1m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Errors: $service",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service\"} |= `error`"
    }
   ]
  },
  {
   "title": "Logs: $service",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service\"}"
    }
   ]
  }
 ]
}