{
 "title": "Golang Monitoring - Echo",
 "description": "This production-ready dashboard provides full-stack visibility for Golang applications using Echo framework and GORM ORM. Monitor critical application metrics including HTTP performance, memory allocation patterns, garbage collection efficiency, and database connection pooling. Features intelligent Apdex scoring, live request tracing, and resource utilization trends with built-in alert thresholds. Perfect for DevOps teams managing high-performance Golang microservices.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(up{job=\"$job\"} == 1)"
   },
   { "name": "target", "label": "Target", "query": "0.05,0.1,0.2,0.3,0.4,0.5" },
   { "name": "tolerated", "label": "Tolerated", "query": "0.1,0.2,0.3,0.4,0.5" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service_version) (target_info{job=~\"$job\"})",
     "legendFormat": "{{service_version}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$job\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex Score: $target s, $tolerated s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(http_server_request_duration_seconds_bucket{le=\"$target\", http_response_status_code=~\"^2..$\"})\n        + (\n            sum(http_server_request_duration_seconds_bucket{le=\"$tolerated\", http_response_status_code=~\"^2..$\"})\n            - sum(http_server_request_duration_seconds_bucket{le=\"$target\", http_response_status_code=~\"^2..$\"})\n        ) / 2\n    ) / sum(http_server_request_duration_seconds_count{job=~\"$job\", http_response_status_code=~\"^2..$\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$job\"}[$__interval]",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\"} == 1)",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(http_server_request_duration_seconds_count{job=~\"$job\", http_response_status_code=~\"^5..$\"} OR on() vector(0))\n    / sum(http_server_request_duration_seconds_count{job=~\"$job\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job)(go_goroutines{job=~\"$job\"})",
     "legendFormat": "{{instance}}: goroutines (avg)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_threads{job=~\"$job\"}) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_body_size_bytes_sum{job=~\"$job\"}[$interval])) + sum(rate(http_server_response_body_size_bytes_sum{job=~\"$job\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_body_size_bytes_sum{job=~\"$job\"}) + sum(http_server_response_body_size_bytes_sum{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Echo Framework", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Apdex Score: $target s, $tolerated s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(http_server_request_duration_seconds_bucket{le=\"$target\", http_response_status_code=~\"^2..$\"}) by (instance)\n        + (\n            sum(http_server_request_duration_seconds_bucket{le=\"$tolerated\", http_response_status_code=~\"^2..$\"}) by (instance)\n            - sum(http_server_request_duration_seconds_bucket{le=\"$target\", http_response_status_code=~\"^2..$\"}) by (instance)\n        ) / 2\n    ) / sum(http_server_request_duration_seconds_count{job=~\"$job\", http_response_status_code=~\"^2..$\"}) by (instance)\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$job\"}[$__rate_interval])) by (http_response_status_code, http_route)",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (http_response_status_code, http_route)",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(http_server_request_body_size_bytes_sum{job=~\"$job\"}) by (http_response_status_code, http_request_method, http_route)",
     "legendFormat": "{{http_request_method}} {{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_sum{job=~\"$job\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_sum{http_response_status_code=~\"^[23]..$\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_sum{http_response_status_code=~\"^[54]..$\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_count{job=~\"$job\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_count{http_response_status_code=~\"^[23]..$\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(http_server_request_duration_seconds_count{http_response_status_code=~\"^[54]..$\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Reserved Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_memstats_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}} (avg)"
      },
      {
       "expr": "deriv(go_memstats_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (deriv)"
      }
     ]
    },
    {
     "title": "Stack Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_memstats_stack_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: stack in use (avg)"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: stack in use (deriv)"
      }
     ]
    },
    {
     "title": "Other Memory Reservations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_memstats_mspan_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: mspan (avg)"
      },
      {
       "expr": "deriv(go_memstats_mspan_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: mspan (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_mcache_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: mcache (avg)"
      },
      {
       "expr": "deriv(go_memstats_mcache_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: mcache (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_buck_hash_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: buck hash (avg)"
      },
      {
       "expr": "deriv(go_memstats_buck_hash_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: buck hash (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_gc_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: gc (avg)"
      },
      {
       "expr": "deriv(go_memstats_gc_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: gc (deriv)"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_memstats_heap_sys_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: heap reserved (avg)"
      },
      {
       "expr": "deriv(go_memstats_heap_sys_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: heap reserved (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_heap_inuse_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: heap in use (avg)"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: heap in use (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_heap_alloc_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: heap alloc (avg)"
      },
      {
       "expr": "deriv(go_memstats_heap_alloc_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: heap alloc (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_heap_idle_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: heap idle (avg)"
      },
      {
       "expr": "deriv(go_memstats_heap_idle_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: heap idle (deriv)"
      },
      {
       "expr": "avg by(instance)(go_memstats_heap_released_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: heap released (avg)"
      },
      {
       "expr": "deriv(go_memstats_heap_released_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: heap released (deriv)"
      }
     ]
    },
    {
     "title": "Heap Allocations Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Frees Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocation Rate, Bytes (IEC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(instance)(rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}: bytes malloced/s (avg)"
      }
     ]
    },
    {
     "title": "Heap Object Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: obj mallocs/s"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(instance)(\n    go_memstats_mallocs_total{job=~\"$job\"}\n    - go_memstats_frees_total{job=~\"$job\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(process_resident_memory_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: resident memory (avg)"
      },
      {
       "expr": "deriv(hypr_process_resident_memory_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: resident memory (deriv)"
      },
      {
       "expr": "avg by(instance)(hypr_process_virtual_memory_bytes{job=~\"$job\"})",
       "legendFormat": "{{instance}}: virtual memory (avg)"
      },
      {
       "expr": "deriv(hypr_process_virtual_memory_bytes{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: virtual memory (deriv)"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Garbage collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC min & max duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_gc_duration_seconds{quantile=\"0\"})",
       "legendFormat": "{{instance}}: min gc time (avg)"
      },
      {
       "expr": "avg by(instance)(go_gc_duration_seconds{quantile=\"1\"})",
       "legendFormat": "{{instance}}: max gc time (avg)"
      },
      {
       "expr": "avg by(instance)(go_gc_duration_seconds{job=~\"$job\"})",
       "legendFormat": "{{instance}}: gc duration (avg)"
      }
     ]
    },
    {
     "title": "Next GC, Bytes (IEC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(instance)(go_memstats_next_gc_bytes{job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=~\"$job\"}[$__rate_interval]) / rate(go_gc_duration_seconds_count{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} avg duration"
      }
     ]
    },
    {
     "title": "Pointer Deferences",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "avg(go_memstats_lookups_total{job=~\"$job\"}) by (instance)",
       "legendFormat": "{{instance}}: pointer deferences (avg)"
      }
     ]
    }
   ]
  },
  {
   "title": "Go File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "avg(process_open_fds{job=~\"$job\"}) by (instance)",
       "legendFormat": "{{instance}} (avg)"
      },
      {
       "expr": "deriv(process_open_fds{job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (deriv)"
      }
     ]
    },
    {
     "title": "File Descriptor Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(process_open_fds{job=~\"$job\"}) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(process_max_fds{job=~\"$job\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}