environment: dev

app:

jwtverifier:
  jwt_issuer: oauth-service
  jwks_url: http://auth:8000/api/v1/.well-known/jwks.json
  jwks_refresh_interval: 1h
  jwks_http_timeout: 10s
  jwt_leeway: 30s
  jwks_unknown_kid_refresh_rate: 5m
  jwks_unknown_kid_wait_max: 10s

rbac:
  adapter: file
  model_path: deployment/maintmode/authz/model.conf
  policy_path: deployment/maintmode/authz/policy.csv

logger:
  level: debug

api_server:
  name: api
  host: 0.0.0.0
  port: 8000

infra_server:
  name: status
  host: 0.0.0.0
  port: 8001

db:
  dsn: <secret:db/dsn>
  driver: postgres
  max_open_conns: 50
  max_idle_conns: 20
  connection_max_lifetime: 10m
  connection_max_idle_time: 5m

tracer:
  collector_host: otel-collector
  collector_port: 4317

redis:
  addr: redis:6379
  password: <secret:redis/password>
  db: 0

external_services:
  auth:
    secret: <secret:external_services/auth/secret>
    protocol: http
    host: auth
    port: 8000

s2s:
