// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1AuditLogParams creates a new GetAPIV1AuditLogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AuditLogParams() *GetAPIV1AuditLogParams {
	return &GetAPIV1AuditLogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AuditLogParamsWithTimeout creates a new GetAPIV1AuditLogParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AuditLogParamsWithTimeout(timeout time.Duration) *GetAPIV1AuditLogParams {
	return &GetAPIV1AuditLogParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AuditLogParamsWithContext creates a new GetAPIV1AuditLogParams object
// with the ability to set a context for a request.
func NewGetAPIV1AuditLogParamsWithContext(ctx context.Context) *GetAPIV1AuditLogParams {
	return &GetAPIV1AuditLogParams{
		Context: ctx,
	}
}

// NewGetAPIV1AuditLogParamsWithHTTPClient creates a new GetAPIV1AuditLogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AuditLogParamsWithHTTPClient(client *http.Client) *GetAPIV1AuditLogParams {
	return &GetAPIV1AuditLogParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AuditLogParams contains all the parameters to send to the API endpoint

	for the get API v1 audit log operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AuditLogParams struct {

	/* Action.

	   Filter by audit action (e.g. assigned, revoked, login_success)
	*/
	Action *string

	/* Actor.

	   Filter by actor (exact match)
	*/
	Actor *string

	/* CreatedFrom.

	   Filter by created_at >= this RFC3339 timestamp
	*/
	CreatedFrom *string

	/* CreatedTo.

	   Filter by created_at <= this RFC3339 timestamp
	*/
	CreatedTo *string

	/* Limit.

	   Number of entries to return (max 100)

	   Default: 100
	*/
	Limit *int64

	/* Offset.

	   Pagination offset
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 audit log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AuditLogParams) WithDefaults() *GetAPIV1AuditLogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 audit log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AuditLogParams) SetDefaults() {
	var (
		limitDefault = int64(100)

		offsetDefault = int64(0)
	)

	val := GetAPIV1AuditLogParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithTimeout(timeout time.Duration) *GetAPIV1AuditLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithContext(ctx context.Context) *GetAPIV1AuditLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithHTTPClient(client *http.Client) *GetAPIV1AuditLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithAction(action *string) *GetAPIV1AuditLogParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetAction(action *string) {
	o.Action = action
}

// WithActor adds the actor to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithActor(actor *string) *GetAPIV1AuditLogParams {
	o.SetActor(actor)
	return o
}

// SetActor adds the actor to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetActor(actor *string) {
	o.Actor = actor
}

// WithCreatedFrom adds the createdFrom to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithCreatedFrom(createdFrom *string) *GetAPIV1AuditLogParams {
	o.SetCreatedFrom(createdFrom)
	return o
}

// SetCreatedFrom adds the createdFrom to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetCreatedFrom(createdFrom *string) {
	o.CreatedFrom = createdFrom
}

// WithCreatedTo adds the createdTo to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithCreatedTo(createdTo *string) *GetAPIV1AuditLogParams {
	o.SetCreatedTo(createdTo)
	return o
}

// SetCreatedTo adds the createdTo to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetCreatedTo(createdTo *string) {
	o.CreatedTo = createdTo
}

// WithLimit adds the limit to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithLimit(limit *int64) *GetAPIV1AuditLogParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) WithOffset(offset *int64) *GetAPIV1AuditLogParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API v1 audit log params
func (o *GetAPIV1AuditLogParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AuditLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Action != nil {

		// query param action
		var qrAction string

		if o.Action != nil {
			qrAction = *o.Action
		}
		qAction := qrAction
		if qAction != "" {

			if err := r.SetQueryParam("action", qAction); err != nil {
				return err
			}
		}
	}

	if o.Actor != nil {

		// query param actor
		var qrActor string

		if o.Actor != nil {
			qrActor = *o.Actor
		}
		qActor := qrActor
		if qActor != "" {

			if err := r.SetQueryParam("actor", qActor); err != nil {
				return err
			}
		}
	}

	if o.CreatedFrom != nil {

		// query param created_from
		var qrCreatedFrom string

		if o.CreatedFrom != nil {
			qrCreatedFrom = *o.CreatedFrom
		}
		qCreatedFrom := qrCreatedFrom
		if qCreatedFrom != "" {

			if err := r.SetQueryParam("created_from", qCreatedFrom); err != nil {
				return err
			}
		}
	}

	if o.CreatedTo != nil {

		// query param created_to
		var qrCreatedTo string

		if o.CreatedTo != nil {
			qrCreatedTo = *o.CreatedTo
		}
		qCreatedTo := qrCreatedTo
		if qCreatedTo != "" {

			if err := r.SetQueryParam("created_to", qCreatedTo); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
