// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ruko1202/maintmode/test/api/client/models"
)

// GetAPIV1AuditLogReader is a Reader for the GetAPIV1AuditLog structure.
type GetAPIV1AuditLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1AuditLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1AuditLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1AuditLogBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1AuditLogInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/audit/log] GetAPIV1AuditLog", response, response.Code())
	}
}

// NewGetAPIV1AuditLogOK creates a GetAPIV1AuditLogOK with default headers values
func NewGetAPIV1AuditLogOK() *GetAPIV1AuditLogOK {
	return &GetAPIV1AuditLogOK{}
}

/*
GetAPIV1AuditLogOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1AuditLogOK struct {
	Payload *models.ApiauthmodelsAuditLogResponse
}

// IsSuccess returns true when this get Api v1 audit log o k response has a 2xx status code
func (o *GetAPIV1AuditLogOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 audit log o k response has a 3xx status code
func (o *GetAPIV1AuditLogOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 audit log o k response has a 4xx status code
func (o *GetAPIV1AuditLogOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 audit log o k response has a 5xx status code
func (o *GetAPIV1AuditLogOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 audit log o k response a status code equal to that given
func (o *GetAPIV1AuditLogOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 audit log o k response
func (o *GetAPIV1AuditLogOK) Code() int {
	return 200
}

func (o *GetAPIV1AuditLogOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogOK %s", 200, payload)
}

func (o *GetAPIV1AuditLogOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogOK %s", 200, payload)
}

func (o *GetAPIV1AuditLogOK) GetPayload() *models.ApiauthmodelsAuditLogResponse {
	return o.Payload
}

func (o *GetAPIV1AuditLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApiauthmodelsAuditLogResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AuditLogBadRequest creates a GetAPIV1AuditLogBadRequest with default headers values
func NewGetAPIV1AuditLogBadRequest() *GetAPIV1AuditLogBadRequest {
	return &GetAPIV1AuditLogBadRequest{}
}

/*
GetAPIV1AuditLogBadRequest describes a response with status code 400, with default header values.

Invalid limit parameter
*/
type GetAPIV1AuditLogBadRequest struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 audit log bad request response has a 2xx status code
func (o *GetAPIV1AuditLogBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 audit log bad request response has a 3xx status code
func (o *GetAPIV1AuditLogBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 audit log bad request response has a 4xx status code
func (o *GetAPIV1AuditLogBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 audit log bad request response has a 5xx status code
func (o *GetAPIV1AuditLogBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 audit log bad request response a status code equal to that given
func (o *GetAPIV1AuditLogBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 audit log bad request response
func (o *GetAPIV1AuditLogBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1AuditLogBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogBadRequest %s", 400, payload)
}

func (o *GetAPIV1AuditLogBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogBadRequest %s", 400, payload)
}

func (o *GetAPIV1AuditLogBadRequest) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1AuditLogBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AuditLogInternalServerError creates a GetAPIV1AuditLogInternalServerError with default headers values
func NewGetAPIV1AuditLogInternalServerError() *GetAPIV1AuditLogInternalServerError {
	return &GetAPIV1AuditLogInternalServerError{}
}

/*
GetAPIV1AuditLogInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetAPIV1AuditLogInternalServerError struct {
	Payload *models.ApierrorsErrorResponse
}

// IsSuccess returns true when this get Api v1 audit log internal server error response has a 2xx status code
func (o *GetAPIV1AuditLogInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 audit log internal server error response has a 3xx status code
func (o *GetAPIV1AuditLogInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 audit log internal server error response has a 4xx status code
func (o *GetAPIV1AuditLogInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 audit log internal server error response has a 5xx status code
func (o *GetAPIV1AuditLogInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 audit log internal server error response a status code equal to that given
func (o *GetAPIV1AuditLogInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 audit log internal server error response
func (o *GetAPIV1AuditLogInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1AuditLogInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogInternalServerError %s", 500, payload)
}

func (o *GetAPIV1AuditLogInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/audit/log][%d] getApiV1AuditLogInternalServerError %s", 500, payload)
}

func (o *GetAPIV1AuditLogInternalServerError) GetPayload() *models.ApierrorsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1AuditLogInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApierrorsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
